(function(){"use strict";let DB,packages=new Map(),lastCheck=0,onUpdated=()=>{};const files=["package.json","summary.json","glossary.json","cards.json","exercises.json","map.json","sources.json"],safe=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function validate(data){const p=data["package.json"];if(!p||p.packageSchemaVersion!==1||!["draft","reviewed","published"].includes(p.status))throw Error("Paquete de contenido inválido");for(const f of files)if(!data[f])throw Error(`Falta ${f}`);for(const [f,k] of [["summary.json","blocks"],["glossary.json","entries"],["cards.json","cards"],["exercises.json","exercises"],["map.json","nodes"],["map.json","edges"],["sources.json","sources"]])if(!Array.isArray(data[f][k]))throw Error(`${f} inválido`);const sourceIds=new Set(data["sources.json"].sources.map(x=>x.id)),visit=x=>{if(Array.isArray(x))x.forEach(visit);else if(x&&typeof x==="object"){if(x.sourceId&&!sourceIds.has(x.sourceId))throw Error("Referencia inexistente");Object.values(x).forEach(visit)}};visit(data);return data}
async function loadLocal(){for(const record of await DB.getAll("contentPackages"))packages.set(record.id,record)}
async function check(force=false){if(!navigator.onLine)return false;if(!force&&Date.now()-lastCheck<15*60*1000)return false;lastCheck=Date.now();const catalog=await fetch(`content/catalog.json?t=${Date.now()}`,{cache:"no-store"}).then(r=>{if(!r.ok)throw Error("No se pudo consultar el catálogo");return r.json()});let changed=false;for(const item of catalog.packages||[]){const id=`${item.subjectId}/${item.unitId}`,old=packages.get(id);if(old?.contentVersion===item.contentVersion)continue;const entries=await Promise.all(files.map(async f=>[f,await fetch(`${item.path}${f}?v=${encodeURIComponent(item.contentVersion)}`,{cache:"no-store"}).then(r=>{if(!r.ok)throw Error(`No se pudo descargar ${f}`);return r.json()})]));const data=validate(Object.fromEntries(entries)),record={id,subjectId:item.subjectId,unitId:item.unitId,title:item.title,contentVersion:item.contentVersion,data,updatedAt:new Date().toISOString()};await DB.installContentPackage(record);packages.set(id,record);changed=true}if(changed)onUpdated();return changed}
function copyButton(label,text){return `<button class="copy-action" data-copy="${safe(text)}">${label}</button>`}
function render(subjectId,tab){const record=[...packages.values()].find(x=>x.subjectId===subjectId);if(!record)return null;const d=record.data;
 if(tab==="summary")return `<div class="content-card zoom-target"><h2>${safe(record.title)}</h2>${d["summary.json"].blocks.map(b=>`<section class="summary-section"><h3>${safe(b.title)}</h3><p class="highlightable" data-block-id="${safe(b.id)}">${safe(b.text)}</p>${copyButton("Copiar párrafo",b.text)}</section>`).join("")}</div>`;
 if(tab==="glossary")return `<div class="content-card zoom-target"><h2>Glosario</h2>${d["glossary.json"].entries.map(e=>`<article class="content-item" data-anchor-id="${safe(e.id)}"><h3>${safe(e.term)}</h3><p>${safe(e.definition)}</p>${copyButton("Copiar definición",`${e.term}: ${e.definition}`)}</article>`).join("")}</div>`;
 if(tab==="cards")return `<div class="content-card zoom-target"><h2>Tarjetas</h2>${d["cards.json"].cards.map(c=>`<article class="content-item" data-anchor-id="${safe(c.id)}"><strong>${safe(c.question)}</strong><p>${safe(c.answer)}</p>${copyButton("Copiar tarjeta",`${c.question}\n${c.answer}`)}</article>`).join("")}</div>`;
 if(tab==="exercises")return `<div class="content-card zoom-target"><h2>Ejercicios</h2>${d["exercises.json"].exercises.map(e=>`<article class="content-item" data-anchor-id="${safe(e.id)}"><h3>${e.origin==="generated"?"Ejercicio generado por Biblioteca LBT":"Ejercicio de fuente"}</h3><p>${safe(e.prompt)}</p>${copyButton("Copiar consigna",e.prompt)}${copyButton("Copiar resolución",(e.solution||[]).join("\n"))}${copyButton("Copiar ejercicio",`${e.prompt}\n${(e.solution||[]).join("\n")}\n${e.result}`)}</article>`).join("")}</div>`;
 return `<div class="content-card zoom-target"><h2>Mapa mental</h2><div class="content-map">${d["map.json"].nodes.map(n=>`<span class="map-node" data-anchor-id="${safe(n.id)}">${safe(n.label)}</span>`).join("")}</div><h3>Referencias</h3>${d["sources.json"].sources.map(s=>`<p>${safe(s.title)}</p>`).join("")}</div>`}
function bind(container){container.querySelectorAll("[data-copy]").forEach(b=>b.onclick=()=>copyText(b.dataset.copy));}
async function copyText(text){try{await navigator.clipboard.writeText(text)}catch(_){const area=document.createElement("textarea");area.value=text;document.body.append(area);area.select();document.execCommand("copy");area.remove()}}
async function init(db,callback){DB=db;onUpdated=callback||onUpdated;await loadLocal();window.addEventListener("online",()=>check(true).catch(showError));document.addEventListener("visibilitychange",()=>{if(!document.hidden)check(false).catch(showError)});check(true).catch(showError)}function showError(error){console.error(error);window.dispatchEvent(new CustomEvent("lbt-content-error",{detail:error.message}))}
window.LBT_CONTENT={init,check,render,bind,copyText,getUnit:(subjectId)=>[...packages.values()].find(x=>x.subjectId===subjectId)};
})();
