(function(){"use strict";
let DB,packages=new Map(),lastCheck=0,onUpdated=()=>{};
const files=["package.json","summary.json","glossary.json","cards.json","exercises.json","map.json","sources.json"];
const safe=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));
function validate(data){const manifest=data["package.json"];if(!manifest||manifest.packageSchemaVersion!==1||manifest.status!=="published")throw Error("Paquete de contenido no publicado o inválido");for(const file of files)if(!data[file])throw Error(`Falta ${file}`);for(const [file,key] of [["summary.json","blocks"],["glossary.json","entries"],["cards.json","cards"],["exercises.json","exercises"],["map.json","nodes"],["map.json","edges"],["sources.json","sources"]])if(!Array.isArray(data[file][key]))throw Error(`${file} inválido`);const sources=new Set(data["sources.json"].sources.map(item=>item.id));const visit=value=>{if(Array.isArray(value))value.forEach(visit);else if(value&&typeof value==="object"){if(value.sourceId&&!sources.has(value.sourceId))throw Error("Referencia inexistente");Object.values(value).forEach(visit)}};visit(data);return data}
async function loadLocal(){for(const record of await DB.getAll("contentPackages"))packages.set(record.id,record)}
function units(subjectId){return [...packages.values()].filter(record=>record.subjectId===subjectId).sort((a,b)=>a.title.localeCompare(b.title,"es")||a.unitId.localeCompare(b.unitId))}
function getUnit(subjectId,unitId){const list=units(subjectId);return list.find(record=>record.unitId===unitId)||null}
async function check(force=false){if(!navigator.onLine)return false;if(!force&&Date.now()-lastCheck<15*60*1000)return false;lastCheck=Date.now();const catalog=await fetch(`content/catalog.json?t=${Date.now()}`,{cache:"no-store"}).then(response=>{if(!response.ok)throw Error("No se pudo consultar el catálogo");return response.json()});let changed=false;for(const item of catalog.packages||[]){const id=`${item.subjectId}/${item.unitId}`,old=packages.get(id);if(old?.contentVersion===item.contentVersion)continue;const entries=await Promise.all(files.map(async file=>[file,await fetch(`${item.path}${file}?v=${encodeURIComponent(item.contentVersion)}`,{cache:"no-store"}).then(response=>{if(!response.ok)throw Error(`No se pudo descargar ${file}`);return response.json()})]));const data=validate(Object.fromEntries(entries)),record={id,subjectId:item.subjectId,unitId:item.unitId,title:item.title,contentVersion:item.contentVersion,data,updatedAt:new Date().toISOString()};await DB.installContentPackage(record);packages.set(id,record);changed=true}if(changed)onUpdated();return changed}
function copyButton(label,text,className=""){return `<button class="copy-action ${className}" data-copy="${safe(text)}">${label}</button>`}
function formula(block){if(block.kind!=="formula")return "";const variables=(block.variables||[]).map(variable=>`<li><strong>${safe(variable.symbol||variable.name)}</strong>: ${safe(variable.definition||variable.meaning||"")}</li>`).join("");return `<div class="formula-box"><div class="formula-visual" aria-label="Representación visual">${safe(block.visual||block.linear||block.latex||block.text)}</div>${block.linear?`<code class="formula-linear">${safe(block.linear)}</code>${copyButton("Copiar texto lineal",block.linear,"copy-linear")}`:""}${block.latex?`<code class="formula-latex">${safe(block.latex)}</code>${copyButton("Copiar LaTeX",block.latex,"copy-latex")}`:""}${variables?`<ul class="formula-variables">${variables}</ul>`:""}</div>`}
function render(subjectId,unitId,tab){const record=getUnit(subjectId,unitId);if(!record)return null;const data=record.data,prefix=`${subjectId}:${unitId}:`;
 if(tab==="summary")return `<div class="content-card zoom-target"><h2>${safe(record.title)}</h2>${data["summary.json"].blocks.map(block=>`<section class="summary-section" data-anchor-id="${safe(prefix+block.id)}"><h3>${safe(block.title)}</h3><p class="highlightable" data-local-block-id="${safe(block.id)}" data-block-id="${safe(prefix+block.id)}">${safe(block.text)}</p>${formula(block)}${copyButton("Copiar párrafo",block.text)}</section>`).join("")}</div>`;
 if(tab==="glossary")return `<div class="content-card zoom-target"><h2>Glosario</h2>${data["glossary.json"].entries.map(entry=>`<article class="content-item" data-anchor-id="${safe(prefix+entry.id)}"><h3>${safe(entry.term)}</h3><p>${safe(entry.definition)}</p>${copyButton("Copiar definición",`${entry.term}: ${entry.definition}`)}</article>`).join("")}</div>`;
 if(tab==="cards")return `<div class="content-card zoom-target"><h2>Tarjetas</h2>${data["cards.json"].cards.map(card=>`<article class="content-item" data-anchor-id="${safe(prefix+card.id)}"><strong>${safe(card.question)}</strong><p>${safe(card.answer)}</p>${copyButton("Copiar tarjeta",`${card.question}\n${card.answer}`)}</article>`).join("")}</div>`;
 if(tab==="exercises")return `<div class="content-card zoom-target"><h2>Ejercicios</h2>${data["exercises.json"].exercises.map(exercise=>`<article class="content-item" data-anchor-id="${safe(prefix+exercise.id)}"><h3>${exercise.origin==="generated"?"Ejercicio generado por Biblioteca LBT":"Ejercicio de fuente"}</h3><p>${safe(exercise.prompt)}</p>${copyButton("Copiar consigna",exercise.prompt)}${copyButton("Copiar resolución",(exercise.solution||[]).join("\n"))}${copyButton("Copiar ejercicio",`${exercise.prompt}\n${(exercise.solution||[]).join("\n")}\n${exercise.result}`)}</article>`).join("")}</div>`;
 const nodes=new Map(data["map.json"].nodes.map(node=>[node.id,node]));return `<div class="content-card zoom-target"><h2>Mapa mental</h2><div class="content-map">${[...nodes.values()].map(node=>`<span class="map-node" data-anchor-id="${safe(prefix+node.id)}">${safe(node.label)}${copyButton("Copiar nodo",node.label)}</span>`).join("")}</div><div class="map-edges">${data["map.json"].edges.map(edge=>`<p class="map-edge" data-from="${safe(edge.from)}" data-to="${safe(edge.to)}"><span>${safe(nodes.get(edge.from)?.label)}</span><strong>${safe(edge.type)}</strong><span>${safe(nodes.get(edge.to)?.label)}</span>${copyButton("Copiar conexión",`${nodes.get(edge.from)?.label} — ${edge.type} — ${nodes.get(edge.to)?.label}`)}</p>`).join("")}</div><h3>Referencias</h3>${data["sources.json"].sources.map(source=>`<p>${safe(source.title)}</p>`).join("")}</div>`}
function bind(container){container.querySelectorAll("[data-copy]").forEach(button=>button.onclick=()=>copyText(button.dataset.copy))}
async function copyText(text){try{await navigator.clipboard.writeText(text)}catch(_){const area=document.createElement("textarea");area.value=text;document.body.append(area);area.select();document.execCommand("copy");area.remove()}}
async function init(db,callback){DB=db;onUpdated=callback||onUpdated;await loadLocal();window.addEventListener("online",()=>check(true).catch(showError));document.addEventListener("visibilitychange",()=>{if(!document.hidden)check(false).catch(showError)});check(true).catch(showError)}
function showError(error){console.error(error);window.dispatchEvent(new CustomEvent("lbt-content-error",{detail:error.message}))}
window.LBT_CONTENT={init,check,render,bind,copyText,getUnit,units};
})();
