(function(){"use strict";
let DB,sync,getContext,notes=[],observer,activeId=null,creating=false,lastCreate=0,zCounter=30;
const colors=["yellow","blue","green","pink"],dirty=new Set(),timers=new Map(),writes=new Set(),now=()=>new Date().toISOString(),uuid=()=>crypto.randomUUID();
const pane=()=>document.querySelector(".content-pane"),layer=()=>document.querySelector(".notes-layer"),clamp=(value,min,max)=>Math.max(min,Math.min(max,value));

function normalize(note){
  const old=note.position||{};
  if(!note.displayMode)note.displayMode=note.collapsed===false?"open":"book";
  note.collapsed=note.displayMode==="book";
  note.position={xRatio:Number.isFinite(old.xRatio)?clamp(old.xRatio,0,1):Number.isFinite(old.x)?clamp(old.x,0,1):.5,documentY:Number.isFinite(old.documentY)?Math.max(0,old.documentY):Number.isFinite(old.y)?Math.max(0,old.y*900):180,offsetX:Number.isFinite(old.offsetX)?old.offsetX:0,offsetY:Number.isFinite(old.offsetY)?old.offsetY:0};
  note.anchor ||= {type:"free",targetId:null,exact:"",prefix:"",suffix:""};return note;
}
async function init(db,driveSync,context){DB=db;sync=driveSync;getContext=context;notes=(await DB.getAll("notes")).map(normalize);window.addEventListener("resize",reflow);document.addEventListener("fullscreenchange",reflow)}
function selectionAnchor(){const selection=getSelection();if(!selection||selection.isCollapsed||!selection.toString().trim())return null;const range=selection.getRangeAt(0),block=range.commonAncestorContainer.parentElement?.closest?.("[data-block-id],[data-anchor-id]")||range.startContainer.parentElement?.closest?.("[data-block-id],[data-anchor-id]");if(!block||!pane()?.contains(block))return null;const exact=selection.toString(),text=block.textContent,index=text.indexOf(exact);return {type:"text-block",targetId:block.dataset.blockId||block.dataset.anchorId,exact,prefix:index>=0?text.slice(Math.max(0,index-32),index):"",suffix:index>=0?text.slice(index+exact.length,index+exact.length+32):""}}
async function create(){if(creating||Date.now()-lastCreate<450)return;const context=getContext(),host=pane();if(!context.subjectId||!context.unitId||!host)return;creating=true;lastCreate=Date.now();try{const stamp=now(),anchor=selectionAnchor(),position={xRatio:.5,documentY:host.scrollTop+host.clientHeight*.45,offsetX:0,offsetY:anchor?24:0},note={id:uuid(),subjectId:context.subjectId,unitId:context.unitId,tab:context.tab,anchor:anchor||{type:"free",targetId:null,exact:"",prefix:"",suffix:""},position,text:"",color:"yellow",collapsed:false,displayMode:"open",contentVersion:context.contentVersion||"legacy",createdAt:stamp,updatedAt:stamp,deletedAt:null};notes.push(note);activeId=note.id;await save(note);render();requestAnimationFrame(()=>document.querySelector(`.note-window[data-id="${note.id}"] textarea`)?.focus())}finally{creating=false}}
async function save(note){note.updatedAt=now();dirty.delete(note.id);const write=DB.put("notes",structuredClone(note));writes.add(write);try{await write;sync?.localChanged()}finally{writes.delete(write)}}
async function flushPendingSaves(){for(const id of [...dirty]){clearTimeout(timers.get(id));timers.delete(id);const note=notes.find(item=>item.id===id);if(note)await save(note)}await Promise.all([...writes])}
async function remove(note){note.deletedAt=now();await save(note);render()}
function candidates(){return [...document.querySelectorAll(".content-pane [data-block-id],.content-pane [data-anchor-id]")]}
function resolveAnchor(note){const all=candidates(),byTarget=note.anchor.targetId&&all.find(element=>(element.dataset.blockId||element.dataset.anchorId)===note.anchor.targetId);if(byTarget)return {element:byTarget,method:"targetId"};const exact=note.anchor.exact&&all.find(element=>element.textContent.includes(note.anchor.exact));if(exact)return {element:exact,method:"exact"};const context=(note.anchor.prefix||note.anchor.suffix)&&all.find(element=>(!note.anchor.prefix||element.textContent.includes(note.anchor.prefix))&&(!note.anchor.suffix||element.textContent.includes(note.anchor.suffix)));if(context)return {element:context,method:"context"};if(note.anchor.type==="free")return {element:null,method:"position"};return null}
function hue(subjectId){return window.LBT_DATA.SUBJECTS.find(subject=>subject.id===subjectId)?.hue||28}
function basePoint(note,resolved){const host=pane();if(resolved?.element){const target=resolved.element.getBoundingClientRect(),rect=host.getBoundingClientRect();return {x:target.left-rect.left+host.scrollLeft+note.position.offsetX,y:target.top-rect.top+host.scrollTop+note.position.offsetY}}return {x:note.position.xRatio*Math.max(1,host.scrollWidth),y:note.position.documentY}}
function bounds(element){const host=pane(),grip=element.querySelector(".note-grip")||element;return {maxX:Math.max(0,host.scrollWidth-Math.min(element.offsetWidth,grip.offsetWidth)),maxY:Math.max(0,Math.max(host.scrollHeight,host.clientHeight)-Math.max(28,grip.offsetHeight)),host}}
function place(element,note,resolved){const point=basePoint(note,resolved),limit=bounds(element),x=clamp(point.x,0,limit.maxX),y=clamp(point.y,0,limit.maxY);element.style.transform=`translate3d(${x}px,${y}px,0)`;element.dataset.x=x;element.dataset.y=y;return {x,y}}
function updatePosition(note,x,y,resolved){const host=pane();note.position.xRatio=clamp(x/Math.max(1,host.scrollWidth),0,1);note.position.documentY=Math.max(0,y);if(resolved?.element){const target=resolved.element.getBoundingClientRect(),rect=host.getBoundingClientRect(),baseX=target.left-rect.left+host.scrollLeft,baseY=target.top-rect.top+host.scrollTop;note.position.offsetX=x-baseX;note.position.offsetY=y-baseY}}
function announce(text){let live=document.querySelector("#notesLive");if(!live){live=document.createElement("div");live.id="notesLive";live.className="sr-only";live.setAttribute("aria-live","polite");document.body.append(live)}live.textContent=text}
function drag(element,note,handle,resolved,{openOnTap=false}={}){let state=null,frame=0,autoFrame=0,pointerY=0;const threshold=6;
  const stopAuto=()=>{if(autoFrame)cancelAnimationFrame(autoFrame);autoFrame=0};
  const autoScroll=()=>{if(!state)return;const host=pane(),rect=host.getBoundingClientRect(),edge=58;let velocity=0;if(pointerY<rect.top+edge)velocity=-Math.min(14,(rect.top+edge-pointerY)/4);else if(pointerY>rect.bottom-edge)velocity=Math.min(14,(pointerY-(rect.bottom-edge))/4);if(velocity){const before=host.scrollTop;host.scrollTop=clamp(before+velocity,0,host.scrollHeight-host.clientHeight);const moved=host.scrollTop-before;state.y+=moved;element.style.transform=`translate3d(${state.x}px,${state.y}px,0)`;autoFrame=requestAnimationFrame(autoScroll)}else autoFrame=0};
  const move=event=>{if(!state)return;pointerY=event.clientY;const dx=event.clientX-state.startX,dy=event.clientY-state.startY;if(!state.dragging&&Math.hypot(dx,dy)>=threshold){state.dragging=true;element.classList.add("dragging");document.documentElement.classList.add("note-dragging")}if(!state.dragging)return;const limit=bounds(element);state.x=clamp(event.clientX-state.hostRect.left+state.host.scrollLeft-state.grabX,0,limit.maxX);state.y=clamp(event.clientY-state.hostRect.top+state.host.scrollTop-state.grabY,0,limit.maxY);if(!frame)frame=requestAnimationFrame(()=>{frame=0;element.style.transform=`translate3d(${state.x}px,${state.y}px,0)`});if(!autoFrame)autoFrame=requestAnimationFrame(autoScroll)};
  const end=async event=>{if(!state)return;const wasDrag=state.dragging,x=state.x,y=state.y;stopAuto();if(frame)cancelAnimationFrame(frame);frame=0;element.classList.remove("dragging");document.documentElement.classList.remove("note-dragging");try{if(handle.hasPointerCapture(event.pointerId))handle.releasePointerCapture(event.pointerId)}catch{}state=null;if(wasDrag){updatePosition(note,x,y,resolved);await save(note);announce("Posición de la nota guardada")}else if(openOnTap)await open(note)};
  handle.addEventListener("pointerdown",event=>{const interactive=event.target.closest("textarea,button,a,input,select");if(event.button!==undefined&&event.button!==0||interactive&&interactive!==handle)return;const host=pane(),hostRect=host.getBoundingClientRect(),rect=element.getBoundingClientRect();activeId=note.id;element.style.zIndex=String(++zCounter);state={startX:event.clientX,startY:event.clientY,grabX:event.clientX-rect.left,grabY:event.clientY-rect.top,x:Number(element.dataset.x),y:Number(element.dataset.y),dragging:false,host,hostRect};pointerY=event.clientY;handle.setPointerCapture(event.pointerId);event.preventDefault()});
  handle.addEventListener("pointermove",move);handle.addEventListener("pointerup",end);handle.addEventListener("pointercancel",end);handle.addEventListener("lostpointercapture",event=>{if(state)end(event)});
}
async function open(note){note.displayMode="open";note.collapsed=false;activeId=note.id;await save(note);render();requestAnimationFrame(()=>document.querySelector(`.note-window[data-id="${note.id}"] textarea`)?.focus())}
async function minimize(note){await flushPendingSaves();note.displayMode="book";note.collapsed=true;await save(note);render();announce("Nota minimizada como libro")}
async function center(note){const host=pane(),resolved=resolveAnchor(note);note.position.xRatio=.5;note.position.documentY=host.scrollTop+host.clientHeight*.35;note.position.offsetX=0;note.position.offsetY=0;if(resolved?.element){note.anchor={type:"free",targetId:null,exact:"",prefix:"",suffix:""}}await save(note);render();announce("Nota centrada")}
function keyboard(element,note,resolved,event){if(event.target.matches("textarea,input,select"))return;const step=event.shiftKey?24:6;if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(event.key)){event.preventDefault();const limit=bounds(element),x=clamp(Number(element.dataset.x)+(event.key==="ArrowLeft"?-step:event.key==="ArrowRight"?step:0),0,limit.maxX),y=clamp(Number(element.dataset.y)+(event.key==="ArrowUp"?-step:event.key==="ArrowDown"?step:0),0,limit.maxY);element.style.transform=`translate3d(${x}px,${y}px,0)`;updatePosition(note,x,y,resolved);save(note);announce("Nota movida")}else if(event.key==="Enter"){event.preventDefault();note.displayMode==="book"?open(note):minimize(note)}else if(event.key==="Escape"&&note.displayMode!=="book"){event.preventDefault();minimize(note)}}
function book(note,host,resolved){const element=document.createElement("button");element.type="button";element.className="note-book";element.dataset.id=note.id;element.style.setProperty("--note-hue",hue(note.subjectId));element.setAttribute("aria-label",note.text?"Abrir libro con nota":"Abrir libro de nota");element.innerHTML='<span aria-hidden="true">▥</span><i aria-hidden="true"></i>';host.append(element);place(element,note,resolved);drag(element,note,element,resolved,{openOnTap:true});element.onkeydown=event=>keyboard(element,note,resolved,event)}
function expanded(note,host,resolved){const element=document.createElement("article");element.className=`post-it note-window note-${note.color}`;element.dataset.id=note.id;element.tabIndex=0;element.style.zIndex=String(note.id===activeId?++zCounter:20);const head=document.createElement("header");head.className="note-grip";head.innerHTML='<strong><span aria-hidden="true">⠿</span> Nota</strong><span class="note-save-state">Guardada</span>';const actions=document.createElement("div");for(const [label,action] of [["Minimizar",()=>minimize(note)],["Centrar nota",()=>center(note)],["Copiar",()=>window.LBT_CONTENT.copyText(note.text)],["Eliminar",()=>remove(note)]]){const button=document.createElement("button");button.type="button";button.textContent=label;button.onclick=action;actions.append(button)}head.append(actions);element.append(head);const textarea=document.createElement("textarea");textarea.value=note.text;textarea.placeholder="Escribí una nota";textarea.setAttribute("aria-label","Texto de la nota");textarea.oninput=()=>{note.text=textarea.value;dirty.add(note.id);element.querySelector(".note-save-state").textContent="Guardando…";clearTimeout(timers.get(note.id));timers.set(note.id,setTimeout(async()=>{timers.delete(note.id);await save(note);element.querySelector(".note-save-state").textContent="Guardada"},300))};textarea.onkeydown=event=>{if(event.key==="Escape"){event.stopPropagation();minimize(note)}};element.append(textarea);const palette=document.createElement("div");palette.className="note-palette";for(const color of colors){const button=document.createElement("button");button.type="button";button.className=`note-color note-${color}`;button.title=`Color ${color}`;button.onclick=async()=>{note.color=color;await save(note);render()};palette.append(button)}element.append(palette);host.append(element);place(element,note,resolved);drag(element,note,head,resolved);element.onkeydown=event=>keyboard(element,note,resolved,event)}
function sizeLayer(){const host=pane(),notesLayer=layer();if(!host||!notesLayer)return;notesLayer.style.width=`${Math.max(host.scrollWidth,host.clientWidth)}px`;notesLayer.style.height=`${Math.max(host.scrollHeight,host.clientHeight)}px`}
function reflow(){requestAnimationFrame(()=>{sizeLayer();document.querySelectorAll(".note-window,.note-book").forEach(element=>{const note=notes.find(item=>item.id===element.dataset.id);if(note)place(element,note,resolveAnchor(note))})})}
function render(){const host=layer();if(!host)return;observer?.disconnect();host.replaceChildren();sizeLayer();const context=getContext(),orphans=[],visible=notes.filter(note=>!note.deletedAt&&note.subjectId===context.subjectId&&note.unitId===context.unitId&&note.tab===context.tab);for(const note of visible){normalize(note);const resolved=resolveAnchor(note);if(!resolved){orphans.push(note);continue}if(resolved.element&&resolved.method!=="targetId"){note.anchor.targetId=resolved.element.dataset.blockId||resolved.element.dataset.anchorId;save(note)}note.displayMode==="book"?book(note,host,resolved):expanded(note,host,resolved)}if(orphans.length){const tray=document.createElement("aside");tray.className="orphan-notes";tray.innerHTML="<strong>Notas sin ubicación</strong>";for(const note of orphans){const button=document.createElement("button");button.textContent=note.text||"Nota vacía";button.onclick=async()=>{note.anchor={type:"free",targetId:null,exact:"",prefix:"",suffix:""};await center(note)};tray.append(button)}host.append(tray)}observer=new ResizeObserver(reflow);observer.observe(pane());observer.observe(document.querySelector(".study-body"));}
window.LBT_NOTES={init,create,render,resolveAnchor,normalize,flushPendingSaves,reflow,reload:async()=>{notes=(await DB.getAll("notes")).map(normalize);render()}};
})();
