(function(){"use strict";let DB,sync,getContext,notes=[];const colors=["yellow","blue","green","pink"];
const now=()=>new Date().toISOString(),uuid=()=>crypto.randomUUID(),active=()=>notes.filter(n=>!n.deletedAt);
async function init(db,driveSync,context){DB=db;sync=driveSync;getContext=context;notes=await DB.getAll("notes")}
function selectionAnchor(){const s=getSelection();if(!s||s.isCollapsed)return null;const range=s.getRangeAt(0),block=range.startContainer.parentElement?.closest("[data-block-id],[data-anchor-id]");if(!block)return null;const exact=s.toString(),text=block.textContent,index=text.indexOf(exact);return {type:"text-block",targetId:block.dataset.blockId||block.dataset.anchorId,exact,prefix:index>=0?text.slice(Math.max(0,index-24),index):"",suffix:index>=0?text.slice(index+exact.length,index+exact.length+24):""}}
async function create(){const c=getContext(),anchor=selectionAnchor()||{type:"free",targetId:null,exact:"",prefix:"",suffix:""},note={id:uuid(),subjectId:c.subjectId,unitId:c.unitId||"legacy",tab:c.tab,anchor,position:{x:.7,y:.15},text:"",color:"yellow",collapsed:false,contentVersion:c.contentVersion||"legacy",createdAt:now(),updatedAt:now(),deletedAt:null};notes.push(note);await save(note);render()}
async function save(note){note.updatedAt=now();await DB.put("notes",note);sync?.localChanged()}
async function remove(note){note.deletedAt=now();await save(note);render()}
function render(){const host=document.querySelector(".study-shell");if(!host)return;host.querySelectorAll(".post-it,.orphan-notes").forEach(x=>x.remove());const c=getContext(),orphans=[];for(const n of active().filter(x=>x.subjectId===c.subjectId)){if(n.anchor.targetId&&!document.querySelector(`[data-block-id="${CSS.escape(n.anchor.targetId)}"],[data-anchor-id="${CSS.escape(n.anchor.targetId)}"]`)){orphans.push(n);continue}const el=document.createElement("article");el.className=`post-it note-${n.color}${n.collapsed?" collapsed":""}`;el.style.left=`${n.position.x*100}%`;el.style.top=`${n.position.y*100}%`;el.dataset.id=n.id;const head=document.createElement("header"),title=document.createElement("strong");title.textContent="Nota";head.append(title);for(const [label,fn] of [["−",async()=>{n.collapsed=!n.collapsed;await save(n);render()}],["Copiar",()=>window.LBT_CONTENT.copyText(n.text)],["×",()=>remove(n)]]){const b=document.createElement("button");b.textContent=label;b.onclick=fn;head.append(b)}el.append(head);const ta=document.createElement("textarea");ta.value=n.text;ta.placeholder="Escribí una nota";ta.oninput=()=>{n.text=ta.value;clearTimeout(ta._t);ta._t=setTimeout(()=>save(n),250)};el.append(ta);const palette=document.createElement("div");for(const color of colors){const b=document.createElement("button");b.className=`note-color note-${color}`;b.title=color;b.onclick=async()=>{n.color=color;await save(n);render()};palette.append(b)}el.append(palette);drag(el,n,head);host.append(el)}if(orphans.length){const tray=document.createElement("aside");tray.className="orphan-notes";const h=document.createElement("strong");h.textContent="Notas sin ubicación";tray.append(h);orphans.forEach(n=>{const b=document.createElement("button");b.textContent=n.text||"Nota vacía";b.onclick=async()=>{n.anchor={type:"free",targetId:null,exact:"",prefix:"",suffix:""};n.position={x:.65,y:.2};await save(n);render()};tray.append(b)});host.append(tray)}}
function drag(el,n,handle){let start=null;const move=e=>{if(!start)return;const rect=el.parentElement.getBoundingClientRect();n.position.x=Math.max(0,Math.min(.9,start.x+(e.clientX-start.cx)/rect.width));n.position.y=Math.max(0,Math.min(.85,start.y+(e.clientY-start.cy)/rect.height));el.style.left=`${n.position.x*100}%`;el.style.top=`${n.position.y*100}%`};handle.onpointerdown=e=>{if(e.target.tagName==="BUTTON")return;start={cx:e.clientX,cy:e.clientY,x:n.position.x,y:n.position.y};handle.setPointerCapture(e.pointerId)};handle.onpointermove=move;handle.onpointerup=async e=>{if(!start)return;start=null;handle.releasePointerCapture(e.pointerId);await save(n)}}
window.LBT_NOTES={init,create,render,reload:async()=>{notes=await DB.getAll("notes");render()}};
})();
