(function(){"use strict";
let DB,sync,getContext,notes=[];const colors=["yellow","blue","green","pink"],now=()=>new Date().toISOString(),uuid=()=>crypto.randomUUID(),dirty=new Set(),timers=new Map(),writes=new Set();
function normalize(note){if(!note.displayMode)note.displayMode=note.collapsed?"book":"expanded";note.collapsed=note.displayMode==="book";note.position={x:Number.isFinite(note.position?.x)?note.position.x:.65,y:Number.isFinite(note.position?.y)?note.position.y:.2};note.anchor ||= {type:"free",targetId:null,exact:"",prefix:"",suffix:""};return note}
async function init(db,driveSync,context){DB=db;sync=driveSync;getContext=context;notes=(await DB.getAll("notes")).map(normalize)}
function selectionAnchor(){const selection=getSelection();if(!selection||selection.isCollapsed)return null;const range=selection.getRangeAt(0),block=range.startContainer.parentElement?.closest("[data-block-id],[data-anchor-id]");if(!block)return null;const exact=selection.toString(),text=block.textContent,index=text.indexOf(exact);return {type:"text-block",targetId:block.dataset.blockId||block.dataset.anchorId,exact,prefix:index>=0?text.slice(Math.max(0,index-24),index):"",suffix:index>=0?text.slice(index+exact.length,index+exact.length+24):""}}
async function create(){const context=getContext();if(!context.subjectId||!context.unitId)return;const stamp=now(),note={id:uuid(),subjectId:context.subjectId,unitId:context.unitId,tab:context.tab,anchor:selectionAnchor()||{type:"free",targetId:null,exact:"",prefix:"",suffix:""},position:{x:.65,y:.2},text:"",color:"yellow",collapsed:false,displayMode:"expanded",contentVersion:context.contentVersion||"legacy",createdAt:stamp,updatedAt:stamp,deletedAt:null};notes.push(note);await save(note);render();requestAnimationFrame(()=>document.querySelector(`.post-it[data-id="${note.id}"] textarea`)?.focus())}
async function save(note){note.updatedAt=now();dirty.delete(note.id);const write=DB.put("notes",note);writes.add(write);try{await write;sync?.localChanged()}finally{writes.delete(write)}}
async function flushPendingSaves(){for(const id of [...dirty]){clearTimeout(timers.get(id));timers.delete(id);const note=notes.find(item=>item.id===id);if(note)await save(note)}await Promise.all([...writes])}
async function remove(note){note.deletedAt=now();await save(note);render()}
function candidates(){return [...document.querySelectorAll("[data-block-id],[data-anchor-id]")]}
function resolveAnchor(note){const all=candidates(),byTarget=note.anchor.targetId&&all.find(element=>(element.dataset.blockId||element.dataset.anchorId)===note.anchor.targetId);if(byTarget)return {element:byTarget,method:"targetId"};const exact=note.anchor.exact&&all.find(element=>element.textContent.includes(note.anchor.exact));if(exact)return {element:exact,method:"exact"};const context=(note.anchor.prefix||note.anchor.suffix)&&all.find(element=>(!note.anchor.prefix||element.textContent.includes(note.anchor.prefix))&&(!note.anchor.suffix||element.textContent.includes(note.anchor.suffix)));if(context)return {element:context,method:"context"};if(note.anchor.type==="free"&&Number.isFinite(note.position.x)&&Number.isFinite(note.position.y))return {element:null,method:"position"};return null}
function hue(subjectId){return window.LBT_DATA.SUBJECTS.find(subject=>subject.id===subjectId)?.hue||28}
function drag(element,note,handle){let start=null;handle.onpointerdown=event=>{if(event.target.closest("button,textarea")&&event.target!==handle)return;start={clientX:event.clientX,clientY:event.clientY,x:note.position.x,y:note.position.y,moved:false};handle.setPointerCapture(event.pointerId)};handle.onpointermove=event=>{if(!start)return;const dx=event.clientX-start.clientX,dy=event.clientY-start.clientY;if(Math.hypot(dx,dy)>5)start.moved=true;const rect=element.parentElement.getBoundingClientRect();note.position.x=Math.max(0,Math.min(.92,start.x+dx/rect.width));note.position.y=Math.max(0,Math.min(.88,start.y+dy/rect.height));element.style.left=`${note.position.x*100}%`;element.style.top=`${note.position.y*100}%`};handle.onpointerup=async event=>{if(!start)return;const moved=start.moved;start=null;element.dataset.moved=String(moved);handle.releasePointerCapture(event.pointerId);await save(note)}}
function book(note,host){const element=document.createElement("button");element.className="note-book";element.dataset.id=note.id;element.style.cssText=`left:${note.position.x*100}%;top:${note.position.y*100}%;--note-hue:${hue(note.subjectId)}`;element.setAttribute("aria-label",note.text?"Abrir nota con contenido":"Abrir nota");element.innerHTML='<span aria-hidden="true">▥</span><i></i>';element.onclick=async event=>{if(element.dataset.moved==="true"){element.dataset.moved="false";return}note.displayMode="expanded";note.collapsed=false;await save(note);render()};drag(element,note,element);host.append(element)}
function expanded(note,host){const element=document.createElement("article");element.className=`post-it note-${note.color}`;element.style.left=`${note.position.x*100}%`;element.style.top=`${note.position.y*100}%`;element.dataset.id=note.id;const head=document.createElement("header");head.innerHTML="<strong>Nota</strong>";for(const [label,action] of [["Minimizar",async()=>{note.displayMode="book";note.collapsed=true;await save(note);render()}],["Copiar",()=>window.LBT_CONTENT.copyText(note.text)],["Eliminar",()=>remove(note)]]){const button=document.createElement("button");button.textContent=label;button.onclick=action;head.append(button)}element.append(head);const textarea=document.createElement("textarea");textarea.value=note.text;textarea.placeholder="Escribí una nota";textarea.oninput=()=>{note.text=textarea.value;dirty.add(note.id);clearTimeout(timers.get(note.id));timers.set(note.id,setTimeout(()=>{timers.delete(note.id);save(note)},250))};element.append(textarea);const palette=document.createElement("div");for(const color of colors){const button=document.createElement("button");button.className=`note-color note-${color}`;button.title=color;button.onclick=async()=>{note.color=color;await save(note);render()};palette.append(button)}element.append(palette);drag(element,note,head);host.append(element)}
function render(){const host=document.querySelector(".study-shell");if(!host)return;host.querySelectorAll(".post-it,.note-book,.orphan-notes").forEach(element=>element.remove());const context=getContext(),orphans=[],visible=notes.filter(note=>!note.deletedAt&&note.subjectId===context.subjectId&&note.unitId===context.unitId&&note.tab===context.tab);for(const note of visible){normalize(note);const resolved=resolveAnchor(note);if(!resolved){orphans.push(note);continue}if(resolved.element&&resolved.method!=="targetId"){note.anchor.targetId=resolved.element.dataset.blockId||resolved.element.dataset.anchorId;save(note)}if(note.displayMode==="book"||note.collapsed)book(note,host);else expanded(note,host)}if(orphans.length){const tray=document.createElement("aside");tray.className="orphan-notes";tray.innerHTML="<strong>Notas sin ubicación</strong>";for(const note of orphans){const button=document.createElement("button");button.textContent=note.text||"Nota vacía";button.onclick=async()=>{note.anchor={type:"free",targetId:null,exact:"",prefix:"",suffix:""};note.position={x:.65,y:.2};note.displayMode="expanded";note.collapsed=false;await save(note);render()};tray.append(button)}host.append(tray)}}
window.LBT_NOTES={init,create,render,resolveAnchor,normalize,flushPendingSaves,reload:async()=>{notes=(await DB.getAll("notes")).map(normalize);render()}};
})();
