(function(){
  "use strict";
  const BANK_URL="content/subjects/quimica_organica/units/resumen-integral/organic-cards-v2.json";
  const SESSION_ID="organic-cards-session-v2";
  let bank=null,host=null,state=null,drag=null;
  const safe=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[char]));
  const fresh=()=>({view:"mode",practice:"both",selected:[],deck:[],index:0,flipped:false,grades:{},history:[],updatedAt:new Date().toISOString()});
  const current=()=>bank?.cards.find(card=>card.id===state.deck[state.index]);
  async function load(){if(!bank){const response=await fetch(`${BANK_URL}?v=2.0.0`,{cache:"no-store"});if(!response.ok)throw Error("No se pudo cargar el banco de Orgánica");bank=await response.json()}const saved=await window.LBT_DB.get("cardProgress",SESSION_ID);state={...fresh(),...(saved?.state||{})};return bank}
  async function save(){state.updatedAt=new Date().toISOString();await window.LBT_DB.put("cardProgress",{id:SESSION_ID,subjectId:"quimica_organica",unitId:"resumen-integral",state,updatedAt:state.updatedAt})}
  function modeCards(){return bank.cards.filter(card=>state.practice==="both"||card.mode===state.practice)}
  function selectedCards(){const selected=new Set(state.selected);return modeCards().filter(card=>selected.has(`${card.unit}|${card.topic}|${card.subtopic}`))}
  function shell(content){host.innerHTML=`<section class="organic-study"><header class="organic-study-head"><span>Química Orgánica</span><h2>Tarjetas de estudio</h2><p>Una pregunta por vez, sin pistas que anticipen la respuesta.</p></header>${content}<div class="organic-clipboard"><button type="button" class="organic-clipboard-toggle" aria-expanded="false" title="Opciones de portapapeles">Copiar</button><div class="organic-clipboard-menu" hidden><button type="button" data-copy-current>Copiar tarjeta actual</button><button type="button" data-copy-review>Copiar incorrectas y dudas</button></div></div><div class="organic-toast" role="status" aria-live="polite" hidden></div></section>`;bindCommon()}
  function bindCommon(){const toggle=host.querySelector(".organic-clipboard-toggle"),menu=host.querySelector(".organic-clipboard-menu");toggle.onclick=()=>{menu.hidden=!menu.hidden;toggle.setAttribute("aria-expanded",String(!menu.hidden))};host.querySelector("[data-copy-current]").onclick=copyCurrent;host.querySelector("[data-copy-review]").onclick=copyReview}
  function toast(message){const element=host.querySelector(".organic-toast");element.textContent=message;element.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>element.hidden=true,2200)}
  async function copy(text){try{await navigator.clipboard.writeText(text)}catch(_){const area=document.createElement("textarea");area.value=text;document.body.append(area);area.select();document.execCommand("copy");area.remove()}toast("Copiado al portapapeles")}
  function renderMode(){shell(`<div class="organic-step"><h3>¿Qué querés practicar?</h3><div class="organic-mode-grid"><button type="button" data-mode="memory"><strong>Memorizar reacciones y teoría</strong><span>Reactivos, productos, condiciones, mecanismos, selectividad y conceptos.</span></button><button type="button" data-mode="synthesis"><strong>Practicar síntesis</strong><span>Compuesto inicial, objetivo, restricciones y rutas posibles.</span></button><button type="button" data-mode="both"><strong>Combinar ambos bancos</strong><span>Mezcla memoria y síntesis en una misma sesión.</span></button></div></div>`);host.querySelectorAll("[data-mode]").forEach(button=>button.onclick=async()=>{state.practice=button.dataset.mode;state.view="topics";state.selected=[];await save();renderTopics()})}
  function key(card){return `${card.unit}|${card.topic}|${card.subtopic}`}
  function toggleKeys(keys,checked){const selected=new Set(state.selected);keys.forEach(value=>checked?selected.add(value):selected.delete(value));state.selected=[...selected]}
  function renderTopics(){const available=modeCards(),selected=new Set(state.selected),unitHtml=bank.units.map(unit=>{const unitCards=available.filter(card=>card.unit===unit.id);if(!unitCards.length)return"";const topics=[...new Set(unitCards.map(card=>card.topic))];const unitKeys=[...new Set(unitCards.map(key))],unitChecked=unitKeys.every(value=>selected.has(value)),unitMixed=!unitChecked&&unitKeys.some(value=>selected.has(value));return `<details class="organic-unit" open><summary><label><input type="checkbox" data-unit="${safe(unit.id)}" ${unitChecked?"checked":""} data-mixed="${unitMixed}"><span>${safe(unit.label)}</span><small>${unitCards.length} tarjetas</small></label></summary><div class="organic-topic-list">${topics.map(topic=>{const topicCards=unitCards.filter(card=>card.topic===topic),topicKeys=[...new Set(topicCards.map(key))],topicChecked=topicKeys.every(value=>selected.has(value)),subtopics=[...new Set(topicCards.map(card=>card.subtopic))];return `<details class="organic-topic"><summary><label><input type="checkbox" data-topic="${safe(unit.id)}|${safe(topic)}" ${topicChecked?"checked":""}><span>${safe(topic)}</span><small>${topicCards.length}</small></label></summary><div class="organic-subtopics">${subtopics.map(subtopic=>{const value=`${unit.id}|${topic}|${subtopic}`,count=topicCards.filter(card=>card.subtopic===subtopic).length;return `<label class="organic-chip"><input type="checkbox" data-subtopic="${safe(value)}" ${selected.has(value)?"checked":""}><span>${safe(subtopic)} <small>${count}</small></span></label>`}).join("")}</div></details>`}).join("")}</div></details>`}).join("");const count=selectedCards().length;shell(`<div class="organic-step organic-selector"><div class="organic-selector-bar"><button type="button" class="soft-btn" data-back-mode>Volver</button><div><strong>Elegí unidades, temas o subtemas</strong><span id="organicSelectionSummary">${state.selected.length} subtemas · ${count} tarjetas · ${state.practice==="both"?"memoria y síntesis":state.practice==="memory"?"memoria":"síntesis"}</span></div><button type="button" data-select-all>Seleccionar todo</button><button type="button" data-clear>Limpiar</button></div><div class="organic-units">${unitHtml}</div><div class="organic-start"><button type="button" class="primary-btn" data-start ${count?"":"disabled"}>Comenzar · ${count} tarjetas</button><p ${count?"hidden":""}>Elegí al menos un subtema con tarjetas.</p></div></div>`);
    host.querySelectorAll("[data-mixed=true]").forEach(input=>input.indeterminate=true);host.querySelector("[data-back-mode]").onclick=()=>{state.view="mode";save();renderMode()};host.querySelector("[data-select-all]").onclick=()=>{state.selected=[...new Set(available.map(key))];renderTopics()};host.querySelector("[data-clear]").onclick=()=>{state.selected=[];renderTopics()};host.querySelectorAll("[data-unit]").forEach(input=>input.onchange=()=>{toggleKeys(available.filter(card=>card.unit===input.dataset.unit).map(key),input.checked);renderTopics()});host.querySelectorAll("[data-topic]").forEach(input=>input.onchange=()=>{const [unit,...rest]=input.dataset.topic.split("|"),topic=rest.join("|");toggleKeys(available.filter(card=>card.unit===unit&&card.topic===topic).map(key),input.checked);renderTopics()});host.querySelectorAll("[data-subtopic]").forEach(input=>input.onchange=()=>{toggleKeys([input.dataset.subtopic],input.checked);renderTopics()});host.querySelector("[data-start]").onclick=startSession;
  }
  async function startSession(){const cards=selectedCards();if(!cards.length){toast("Elegí al menos un tema");return}state.deck=cards.map(card=>card.id);state.index=0;state.flipped=false;state.grades={};state.history=[];state.view="session";await save();renderSession()}
  function answerHtml(card){return `<p>${safe(card.back)}</p><button type="button" class="organic-summary-link" data-summary-target="${safe(card.summaryTarget)}" onpointerdown="event.stopPropagation()">Ver explicación en el resumen</button>`}
  function renderSession(){if(!state.deck.length){state.view="topics";renderTopics();return}const card=current();if(!card){state.index=0;return renderSession()}const graded=Object.keys(state.grades).length;shell(`<div class="organic-session"><div class="organic-session-top"><button type="button" data-back-topics>Volver a temas</button><strong>Tarjeta ${state.index+1} de ${state.deck.length}</strong><button type="button" data-finish>Finalizar</button></div><div class="organic-progress"><i style="--progress:${Math.round((state.index+1)/state.deck.length*100)}%"></i></div><div class="organic-swipe-stage"><span class="swipe-label swipe-bad">Mal</span><span class="swipe-label swipe-good">Bien</span><span class="swipe-label swipe-review">Repasar</span><article class="organic-card ${state.flipped?"flipped":""}" tabindex="0" role="button" aria-label="${state.flipped?"Ocultar respuesta":"Mostrar respuesta"}"><div class="organic-card-inner"><section class="organic-card-face organic-front"><p>${safe(card.front)}</p><small>Tocá o presioná espacio para ver la respuesta</small></section><section class="organic-card-face organic-back"><div>${answerHtml(card)}</div><small>Clasificá con un gesto o con los botones</small></section></div></article></div><div class="organic-grade-actions"><button type="button" data-grade="bad" ${state.flipped?"":"disabled"}>Mal</button><button type="button" data-grade="review" ${state.flipped?"":"disabled"}>Repasar</button><button type="button" data-grade="good" ${state.flipped?"":"disabled"}>Bien</button></div><div class="organic-session-nav"><button type="button" data-prev ${state.index===0?"disabled":""}>Anterior</button><button type="button" data-undo ${state.history.length?"":"disabled"}>Deshacer última</button><button type="button" data-next ${state.index===state.deck.length-1?"disabled":""}>Siguiente</button></div><p class="organic-classified">${graded} de ${state.deck.length} clasificadas</p></div>`);bindSession(card)}
  function flip(){state.flipped=!state.flipped;save();renderSession()}
  function bindSession(card){const element=host.querySelector(".organic-card");element.onclick=event=>{if(event.target.closest(".organic-summary-link"))return;flip()};element.onkeydown=event=>{if(event.key===" "||event.key==="Enter"){event.preventDefault();flip()}else if(state.flipped&&event.key==="ArrowLeft")grade("bad","left");else if(state.flipped&&event.key==="ArrowDown")grade("review","down");else if(state.flipped&&event.key==="ArrowRight")grade("good","right")};element.onpointerdown=event=>{if(!state.flipped)return;drag={id:event.pointerId,x:event.clientX,y:event.clientY,dx:0,dy:0};element.setPointerCapture(event.pointerId)};element.onpointermove=event=>{if(!drag||drag.id!==event.pointerId)return;drag.dx=event.clientX-drag.x;drag.dy=Math.max(0,event.clientY-drag.y);const horizontal=Math.abs(drag.dx)>drag.dy,dx=horizontal?drag.dx:0,dy=horizontal?0:drag.dy;element.style.transform=`translate(${dx}px,${dy}px) rotate(${dx/24}deg)`;element.closest(".organic-swipe-stage").dataset.intent=horizontal?(dx>0?"good":"bad"):"review"};element.onpointerup=event=>{if(!drag)return;const {dx,dy}=drag;drag=null;if(Math.abs(dx)>=90&&Math.abs(dx)>dy)grade(dx>0?"good":"bad",dx>0?"right":"left");else if(dy>=90)grade("review","down");else{element.style.transform="";delete element.closest(".organic-swipe-stage").dataset.intent}};host.querySelectorAll("[data-grade]").forEach(button=>button.onclick=()=>grade(button.dataset.grade,button.dataset.grade));host.querySelector("[data-prev]").onclick=()=>move(-1);host.querySelector("[data-next]").onclick=()=>move(1);host.querySelector("[data-back-topics]").onclick=()=>{state.view="topics";save();renderTopics()};host.querySelector("[data-finish]").onclick=finish;host.querySelector("[data-undo]").onclick=undo;host.querySelector("[data-summary-target]").onclick=event=>openSummary(event.currentTarget.dataset.summaryTarget)}
  async function grade(value,direction){if(!state.flipped)return;const card=current(),previous=state.grades[card.id]||null;state.history.push({cardId:card.id,previous,index:state.index});state.grades[card.id]=value;await window.LBT_DB.put("cardProgress",{id:`organic-card:${card.id}`,subjectId:"quimica_organica",unitId:"resumen-integral",cardId:card.id,grade:value,updatedAt:new Date().toISOString()});const element=host.querySelector(".organic-card");element.classList.add(`exit-${direction}`);setTimeout(async()=>{if(state.index<state.deck.length-1)state.index++;else state.view="results";state.flipped=false;await save();state.view==="results"?renderResults():renderSession()},260)}
  async function move(offset){state.index=Math.max(0,Math.min(state.deck.length-1,state.index+offset));state.flipped=false;await save();renderSession()}
  async function undo(){const last=state.history.pop();if(!last)return;if(last.previous)state.grades[last.cardId]=last.previous;else delete state.grades[last.cardId];state.index=last.index;state.flipped=false;await save();renderSession()}
  async function finish(){state.view="results";await save();renderResults()}
  function resultCards(values){return state.deck.filter(id=>values.includes(state.grades[id]))}
  function renderResults(){const good=resultCards(["good"]),bad=resultCards(["bad"]),review=resultCards(["review"]),total=good.length+bad.length+review.length,percent=total?Math.round(good.length/total*100):0,topics=[...new Set(state.deck.map(id=>bank.cards.find(card=>card.id===id)?.unitLabel).filter(Boolean))];shell(`<div class="organic-results"><h3>Resumen de la sesión</h3><div class="organic-result-grid"><article><strong>${good.length}</strong><span>Bien</span></article><article><strong>${bad.length}</strong><span>Mal</span></article><article><strong>${review.length}</strong><span>Repasar</span></article><article><strong>${percent}%</strong><span>Aciertos</span></article></div><p><strong>Temas incluidos:</strong> ${safe(topics.join(", "))}</p><div class="organic-result-actions"><button data-repeat="bad" ${bad.length?"":"disabled"}>Repetir incorrectas</button><button data-repeat="review" ${review.length?"":"disabled"}>Repetir repasar</button><button data-repeat="bad,review" ${bad.length+review.length?"":"disabled"}>Incorrectas y dudas</button><button data-new> Nueva selección</button><button data-copy-review>Copiar incorrectas y dudas</button></div></div>`);host.querySelectorAll("[data-repeat]").forEach(button=>button.onclick=()=>repeat(button.dataset.repeat.split(",")));host.querySelector("[data-new]").onclick=()=>{state.view="topics";renderTopics()};host.querySelectorAll("[data-copy-review]").forEach(button=>button.onclick=copyReview)}
  async function repeat(grades){state.deck=resultCards(grades);state.index=0;state.flipped=false;state.grades={};state.history=[];state.view="session";await save();renderSession()}
  function cardText(card,includeAnswer=true,grade=""){return `Pregunta:\n${card.front}${includeAnswer?`\n\nRespuesta correcta:\n${card.back}`:""}${grade?`\n\nClasificación: ${grade}`:""}\nContexto: ${card.unitLabel} · ${card.topic}\nEnlace interno: #${card.summaryTarget}`}
  async function copyCurrent(){const card=current();if(!card){toast("No hay una tarjeta actual");return}copy(`Estoy estudiando Química Orgánica y necesito ayuda con esta tarjeta.\n\n${cardText(card,state.flipped)}\n\nNecesito que revises si la respuesta es correcta y me expliques el razonamiento sin asumir pasos intermedios.`)}
  async function copyReview(){const ids=resultCards(["bad","review"]);if(!ids.length){toast("Todavía no hay incorrectas ni dudas");return}const intro="Estas son las tarjetas de Química Orgánica que respondí mal o necesito repasar. Ayudame a revisarlas una por una. Para cada tarjeta, explicá primero qué concepto debía reconocer, después resolvela y finalmente indicá por qué mi confusión podría ser frecuente.";copy(`${intro}\n\n${ids.map((id,index)=>`${index+1}. ${cardText(bank.cards.find(card=>card.id===id),true,state.grades[id])}`).join("\n\n---\n\n")}`)}
  function openSummary(target){save().catch(()=>{});sessionStorage.setItem("organic-card-return","1");const started=Date.now(),attach=()=>{const frame=document.querySelector(".rich-document");if(!frame&&Date.now()-started<5000)return setTimeout(attach,60);if(!frame)return;frame.src=`${frame.src.split("#")[0]}#${target}`;let back=document.querySelector("#organicReturnToCard");if(!back){back=document.createElement("button");back.id="organicReturnToCard";back.className="organic-return";back.textContent="Volver a la tarjeta";back.onclick=()=>window.dispatchEvent(new CustomEvent("lbt-open-study-tab",{detail:{tab:"cards"}}));document.body.append(back)}};window.dispatchEvent(new CustomEvent("lbt-open-study-tab",{detail:{tab:"summary"}}));attach()}
  async function bind(container){host=container.querySelector("[data-organic-cards]");if(!host)return;document.querySelector("#organicReturnToCard")?.remove();try{await load();if(state.view==="session"&&state.deck.length)renderSession();else if(state.view==="results")renderResults();else if(state.view==="topics")renderTopics();else renderMode()}catch(error){host.innerHTML=`<div class="empty-state"><strong>No se pudieron cargar las tarjetas</strong><p>${safe(error.message)}</p></div>`}}
  window.LBT_ORGANIC_CARDS={bind};
})();
