(function(){
  "use strict";
  const SYNC_STORES=new Set(["kv","subjects","events","highlights","cardProgress","exerciseProgress","notes","studySessions","collections","bookmarks","activityLog"]);
  let client=null,user=null,DB=null,channel=null,applying=false,onApplied=()=>{};
  const keyFor=(store,value)=>store==="kv"?value.key:value.id;
  const clock=value=>Date.parse(value?.updatedAt||value?.deletedAt||value?.createdAt||0)||0;
  const newer=(local,remote)=>!local||clock(remote)>=clock(local)?remote:local;
  async function applyRow(row){if(!row||!SYNC_STORES.has(row.store))return;const local=await DB.get(row.store,row.record_key),winner=newer(local,row.payload);if(winner!==local){applying=true;try{await DB.put(row.store,winner)}finally{applying=false}}}
  async function pull(){if(!user)return;let from=0;while(true){const {data,error}=await client.from("user_records").select("store,record_key,payload,updated_at").range(from,from+999);if(error)throw error;for(const row of data)await applyRow(row);if(data.length<1000)break;from+=1000}await onApplied()}
  async function pushLocal(){if(!user)return;const rows=[];for(const store of SYNC_STORES)for(const item of await DB.getAll(store)){const key=keyFor(store,item);if(key)rows.push({user_id:user.id,store,record_key:key,payload:item,updated_at:item.updatedAt||item.createdAt||new Date().toISOString()})}for(let i=0;i<rows.length;i+=250){const {error}=await client.from("user_records").upsert(rows.slice(i,i+250),{onConflict:"user_id,store,record_key"});if(error)throw error}}
  async function queueChange(store,value){if(applying||!user||!SYNC_STORES.has(store))return;const record_key=keyFor(store,value);if(!record_key)return;const {error}=await client.from("user_records").upsert({user_id:user.id,store,record_key,payload:value,updated_at:value.updatedAt||value.createdAt||new Date().toISOString()},{onConflict:"user_id,store,record_key"});if(error)window.dispatchEvent(new CustomEvent("solved-cloud-error",{detail:error.message}))}
  async function remove(store,key){if(applying||!user||!SYNC_STORES.has(store))return;const {error}=await client.from("user_records").delete().eq("user_id",user.id).eq("store",store).eq("record_key",key);if(error)window.dispatchEvent(new CustomEvent("solved-cloud-error",{detail:error.message}))}
  async function init(db,callback){client=window.SOLVED_AUTH?.client;DB=db;onApplied=callback||onApplied;await window.SOLVED_AUTH?.ready;const {data}=client?await client.auth.getUser():{data:{}};user=data?.user||null;if(!user)return {connected:false};await pull();await pushLocal();const refreshContent=()=>window.LBT_CONTENT?.syncSupabase?.().then(()=>onApplied()).catch(error=>window.dispatchEvent(new CustomEvent("solved-cloud-error",{detail:error.message})));channel=client.channel(`solved:${user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"user_records",filter:`user_id=eq.${user.id}`},async payload=>{if(payload.eventType==="DELETE")return;await applyRow(payload.new);await onApplied()}).on("postgres_changes",{event:"*",schema:"public",table:"official_content"},refreshContent).on("postgres_changes",{event:"*",schema:"public",table:"user_content",filter:`user_id=eq.${user.id}`},refreshContent).on("postgres_changes",{event:"*",schema:"public",table:"content_preferences",filter:`user_id=eq.${user.id}`},refreshContent).subscribe();return {connected:true}}
  async function close(){if(channel&&client)await client.removeChannel(channel);channel=null}
  window.addEventListener("beforeunload",()=>close());
  window.SOLVED_CLOUD={init,queueChange,remove,pull,isConnected:()=>!!user};
})();
