(function(){
  "use strict";
  const SYNC_STORES=new Set(["kv","subjects","events","highlights","cardProgress","exerciseProgress","notes","studySessions","collections","bookmarks","activityLog"]);
  let client=null,user=null,DB=null,channel=null,applying=false,onApplied=()=>{},bootstrapPromise=null,bootstrapScheduled=false;
  const keyFor=(store,value)=>store==="kv"?value.key:value.id;
  const clock=value=>Date.parse(value?.updatedAt||value?.deletedAt||value?.createdAt||0)||0;
  const newer=(local,remote)=>!local||clock(remote)>=clock(local)?remote:local;
  const cloudError=error=>window.dispatchEvent(new CustomEvent("solved-cloud-error",{detail:error?.message||String(error)}));
  const materialRow=item=>({id:item.id,user_id:user.id,subject_id:item.subjectId,section:item.section,type:item.type,title:item.title||null,text_content:item.textContent||null,file_path:item.filePath||null,original_filename:item.originalFilename||null,mime_type:item.mimeType||null,"order":item.order||0,created_at:item.createdAt,updated_at:item.updatedAt,deleted_at:item.deletedAt||null});
  const materialRecord=row=>({id:row.id,userId:row.user_id,subjectId:row.subject_id,section:row.section,type:row.type,title:row.title||"",textContent:row.text_content||"",filePath:row.file_path||null,originalFilename:row.original_filename||null,mimeType:row.mime_type||null,order:row.order||0,createdAt:row.created_at,updatedAt:row.updated_at,deletedAt:row.deleted_at||null});
  const officialRecord=row=>({id:row.id,subjectId:row.subject_id,section:row.section,type:row.type,title:row.title||"",textContent:row.text_content||"",originalFilename:row.original_filename||null,mimeType:row.mime_type||null,order:row.order||0,createdAt:row.created_at,updatedAt:row.updated_at,deletedAt:row.deleted_at||null,origin:"official"});
  async function pullOfficialMaterials(){if(!client)return;const {data,error}=await client.from("official_materials").select("*").is("deleted_at",null).order("order");if(error)throw error;const active=new Set((data||[]).map(row=>row.id));for(const row of data||[]){applying=true;try{await DB.put("officialMaterials",officialRecord(row))}finally{applying=false}}for(const local of await DB.getAll("officialMaterials"))if(!active.has(local.id)){applying=true;try{await DB.del("officialMaterials",local.id)}finally{applying=false}}}
  async function publishOfficialMaterial(item){const profile=window.SOLVED_AUTH?.profile();if(!client||profile?.role!=="owner")throw Error("Sólo una cuenta autorizada de Sol puede publicar en la biblioteca");if(!["text","markdown","html"].includes(item.type))throw Error("El material oficial debe ser texto, Markdown o HTML");const row={subject_id:item.subjectId,section:item.section,type:item.type,title:item.title||null,text_content:item.textContent,original_filename:item.originalFilename||null,mime_type:item.mimeType||null,"order":item.order||0},query=item.origin==="official"?client.from("official_materials").update(row).eq("id",item.id):client.from("official_materials").insert(row),{data,error}=await query.select().single();if(error)throw error;await pullOfficialMaterials();return officialRecord(data)}
  async function deleteOfficialMaterial(id){const profile=window.SOLVED_AUTH?.profile();if(!client||profile?.role!=="owner")throw Error("Sólo una cuenta autorizada de Sol puede eliminar material de la biblioteca");const {error}=await client.from("official_materials").delete().eq("id",id);if(error)throw error;await pullOfficialMaterials();await onApplied()}
  async function uploadMaterialBlob(item){if(!item.blobContent)return item.filePath||null;const path=`${user.id}/${item.id}/${item.originalFilename||"material.pdf"}`,{error}=await client.storage.from("user-materials").upload(path,item.blobContent,{contentType:item.mimeType||"application/octet-stream",upsert:true});if(error)throw error;return path}
  async function pullMaterials(){const {data,error}=await client.from("user_materials").select("*").order("order");if(error)throw error;for(const row of data||[]){const remote=materialRecord(row),local=await DB.get("userMaterials",remote.id);if(newer(local,remote)!==remote)continue;if(remote.filePath&&!remote.deletedAt){const {data:blob,error:downloadError}=await client.storage.from("user-materials").download(remote.filePath);if(!downloadError)remote.blobContent=blob}applying=true;try{await DB.put("userMaterials",remote)}finally{applying=false}}}
  async function pushMaterial(item){const next={...item,filePath:await uploadMaterialBlob(item)},{error}=await client.from("user_materials").upsert(materialRow(next),{onConflict:"id"});if(error)throw error;if(next.filePath!==item.filePath){applying=true;try{await DB.put("userMaterials",next)}finally{applying=false}}}
  async function applyRow(row){if(!row||!SYNC_STORES.has(row.store))return;const local=await DB.get(row.store,row.record_key),winner=newer(local,row.payload);if(winner!==local){applying=true;try{await DB.put(row.store,winner)}finally{applying=false}}}
  async function pull(){if(!user)return;let from=0;while(true){const {data,error}=await client.from("user_records").select("store,record_key,payload,updated_at").range(from,from+999);if(error)throw error;for(const row of data)await applyRow(row);if(data.length<1000)break;from+=1000}await pullMaterials();await onApplied()}
  async function pushLocal(){if(!user)return;const rows=[];for(const store of SYNC_STORES)for(const item of await DB.getAll(store)){const key=keyFor(store,item);if(key)rows.push({user_id:user.id,store,record_key:key,payload:item,updated_at:item.updatedAt||item.createdAt||new Date().toISOString()})}for(let i=0;i<rows.length;i+=250){const {error}=await client.from("user_records").upsert(rows.slice(i,i+250),{onConflict:"user_id,store,record_key"});if(error)throw error}for(const item of await DB.getAll("userMaterials"))await pushMaterial(item)}
  async function queueChange(store,value){if(applying||!user)return;if(store==="userMaterials"){try{await pushMaterial(value)}catch(error){cloudError(error)}return}if(!SYNC_STORES.has(store))return;const record_key=keyFor(store,value);if(!record_key)return;const {error}=await client.from("user_records").upsert({user_id:user.id,store,record_key,payload:value,updated_at:value.updatedAt||value.createdAt||new Date().toISOString()},{onConflict:"user_id,store,record_key"});if(error)cloudError(error)}
  async function remove(store,key){if(applying||!user)return;if(store==="userMaterials"){const {error}=await client.from("user_materials").delete().eq("user_id",user.id).eq("id",key);if(error)cloudError(error);return}if(!SYNC_STORES.has(store))return;const {error}=await client.from("user_records").delete().eq("user_id",user.id).eq("store",store).eq("record_key",key);if(error)cloudError(error)}
  function subscribeRealtime(){if(!client||!user||channel)return;const refreshContent=()=>window.LBT_CONTENT?.syncSupabase?.().then(()=>onApplied()).catch(cloudError),refreshOfficial=()=>pullOfficialMaterials().then(onApplied).catch(cloudError);channel=client.channel(`solved:${user.id}`).on("postgres_changes",{event:"*",schema:"public",table:"user_records",filter:`user_id=eq.${user.id}`},async payload=>{if(payload.eventType==="DELETE")return;await applyRow(payload.new);await onApplied()}).on("postgres_changes",{event:"*",schema:"public",table:"official_materials"},refreshOfficial).on("postgres_changes",{event:"*",schema:"public",table:"official_content"},refreshContent).on("postgres_changes",{event:"*",schema:"public",table:"user_content",filter:`user_id=eq.${user.id}`},refreshContent).on("postgres_changes",{event:"*",schema:"public",table:"content_preferences",filter:`user_id=eq.${user.id}`},refreshContent).subscribe()}
  function bootstrap(){if(bootstrapPromise)return bootstrapPromise;bootstrapPromise=(async()=>{await pullOfficialMaterials();if(!user)return;subscribeRealtime();await pull();await pushLocal()})().catch(error=>{cloudError(error);return false}).finally(()=>{bootstrapPromise=null});return bootstrapPromise}
  function scheduleBootstrap(){if(bootstrapScheduled)return;const run=()=>{bootstrapScheduled=false;bootstrap()};if(document.documentElement.dataset.appReady==="true"){setTimeout(run,0);return}bootstrapScheduled=true;window.addEventListener("lbt-app-ready",run,{once:true})}
  async function init(db,callback){client=window.SOLVED_AUTH?.client;DB=db;onApplied=callback||onApplied;await window.SOLVED_AUTH?.ready;const profile=window.SOLVED_AUTH?.profile();user=client&&profile?.mode==="authorized-google"&&profile.sub?{id:profile.sub}:null;subscribeRealtime();scheduleBootstrap();return {connected:!!user,background:true}}
  async function close(){if(channel&&client)await client.removeChannel(channel);channel=null}
  window.addEventListener("online",()=>scheduleBootstrap());
  window.addEventListener("beforeunload",()=>close());
  window.SOLVED_CLOUD={init,queueChange,remove,pull,pullOfficialMaterials,publishOfficialMaterial,deleteOfficialMaterial,isConnected:()=>!!user};
})();