import {test,expect} from "@playwright/test";

const ready=async page=>{await page.goto("/");await page.waitForFunction(()=>document.documentElement.dataset.appReady==="true")};
const openPhysics=async page=>{await ready(page);await page.locator('[data-open="fisica1"]').first().click();await page.locator("#studyUnit").selectOption("demo")};
const startPassive=async(page,start=1_700_000_000_000)=>{await page.evaluate(value=>{window.__realNow=Date.now;window.__studyNow=value;Date.now=()=>window.__studyNow;LBT_UTILS.noteStudyInteraction()},start);await expect.poll(()=>page.evaluate(async()=>{const state=await navigator.locks.query();return state.held.some(lock=>lock.name==="lbt-passive-study")})).toBe(true)};
const advance=async(page,milliseconds)=>page.evaluate(value=>{window.__studyNow+=value},milliseconds);
const restoreClock=async page=>page.evaluate(()=>{Date.now=window.__realNow;delete window.__realNow;delete window.__studyNow});
const passive=page=>page.evaluate(()=>LBT_DB.getAll("activityLog").then(items=>items.filter(item=>item.type==="passive-study-session")));

test("@desktop personaliza, persiste y restaura el color de una materia",async({page})=>{
  await openPhysics(page);await page.locator("#themeBtn").click();await page.locator("#appearanceSubject").selectOption("fisica1");await page.locator('[data-subject-hue="132"]').click();
  await expect(page.locator("html")).toHaveCSS("--subject-hue","132");expect(await page.evaluate(()=>LBT_DB.get("kv","settings").then(row=>row.value.subjectHueOverrides.fisica1))).toBe(132);
  await page.evaluate(()=>{const node=document.querySelector('[data-block-id="fisica1:demo:demo-intro"]'),range=document.createRange();range.selectNodeContents(node);const selection=getSelection();selection.removeAllRanges();selection.addRange(range)});await page.locator("#highlightBtn").click();await page.locator("#newNoteBtn").click();await page.getByRole("button",{name:"Minimizar"}).click();
  await expect(page.locator("mark.study-highlight")).toHaveCSS("--subject-hue","132");await expect(page.locator(".note-book")).toHaveCSS("--note-hue","132");
  await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.appReady==="true");await page.locator('[data-open="fisica1"]').first().click();await expect(page.locator("html")).toHaveCSS("--subject-hue","132");await page.locator("#themeBtn").click();await page.locator("#resetSubjectColor").click();await expect(page.locator("html")).toHaveCSS("--subject-hue","214");expect(await page.evaluate(()=>LBT_DB.get("kv","settings").then(row=>row.value.subjectHueOverrides?.fisica1))).toBeUndefined();
});

test("@desktop temporizador running y paused corta y bloquea estudio detectado",async({page})=>{
  await openPhysics(page);await startPassive(page);await advance(page,120_000);await page.locator("#timerBtn").click();await page.locator('[data-minutes="25"]').click();
  await expect.poll(()=>passive(page).then(items=>items.length)).toBe(1);let records=await passive(page);expect(records[0].metadata.durationMs).toBe(120_000);expect(records[0]).toEqual(expect.objectContaining({subjectId:"fisica1",unitId:"demo",metadata:expect.objectContaining({tab:"summary"})}));
  await page.evaluate(()=>LBT_UTILS.noteStudyInteraction());await expect.poll(()=>page.evaluate(async()=>{const state=await navigator.locks.query();return state.held.some(lock=>lock.name==="lbt-passive-study")})).toBe(false);await page.locator('[data-timer="pause"]').click();await page.evaluate(()=>LBT_UTILS.noteStudyInteraction());await expect.poll(()=>page.evaluate(async()=>{const state=await navigator.locks.query();return state.held.some(lock=>lock.name==="lbt-passive-study")})).toBe(false);expect((await passive(page))).toHaveLength(1);
  await page.locator('[data-timer="cancel"]').click();await expect.poll(()=>page.evaluate(()=>LBT_DB.getAll("studySessions").then(items=>items[0]?.status))).toBe("cancelled");await page.evaluate(()=>LBT_UTILS.noteStudyInteraction());await expect.poll(()=>page.evaluate(async()=>{const state=await navigator.locks.query();return state.held.some(lock=>lock.name==="lbt-passive-study")})).toBe(true);await page.evaluate(()=>LBT_UTILS.transitionStudyContext());await restoreClock(page);
});

test("@desktop materia, unidad, pestaña y salida generan tramos separados",async({page})=>{
  await openPhysics(page);await startPassive(page);await advance(page,60_000);const exercises=page.getByRole("button",{name:"Ejercicios"});await exercises.click();await expect(page.locator("#studyPage")).toHaveAttribute("data-tab","exercises");await startPassive(page,1_700_000_060_000);await advance(page,30_000);await page.locator("#studyUnit").selectOption("formula-map");await expect(page.locator("#studyPage")).toHaveAttribute("data-unit-id","formula-map");await startPassive(page,1_700_000_090_000);await advance(page,20_000);await page.evaluate(()=>window.dispatchEvent(new CustomEvent("lbt-open-content",{detail:{subjectId:"analisis1"}})));await expect(page.locator("#studyTitle")).toHaveText("Análisis I");await startPassive(page,1_700_000_110_000);await advance(page,10_000);await page.locator("#backStudy").click();await restoreClock(page);
  const records=await passive(page),segments=records.map(item=>[item.subjectId,item.unitId,item.metadata.tab,item.metadata.durationMs]).sort((a,b)=>b[3]-a[3]);expect(segments).toEqual([["fisica1","demo","summary",60_000],["fisica1","demo","exercises",30_000],["fisica1","formula-map","exercises",20_000],["analisis1","legacy","summary",10_000]]);await expect.poll(()=>page.evaluate(async()=>{const state=await navigator.locks.query();return state.held.some(lock=>lock.name==="lbt-passive-study")})).toBe(false);
});

test("@desktop detalle semanal agrupa estudio detectado por materia y sección",async({page})=>{
  await ready(page);await page.evaluate(async()=>{await LBT_UTILS.saveDetectedStudy(2_700_000,{subjectId:"fisica1",unitId:"demo",tab:"summary"});await LBT_UTILS.saveDetectedStudy(1_500_000,{subjectId:"fisica1",unitId:"demo",tab:"exercises"});await LBT_UTILS.saveDetectedStudy(600_000,{subjectId:"fisica1",unitId:"formula-map",tab:"formulas"});await LBT_UTILS.renderWeekly()});await page.getByText("Detalle del estudio detectado").click();const detail=page.locator(".detected-study-detail");await expect(detail).toContainText("Física I — 1 h 20 min");await expect(detail).toContainText("Resumen · demo");await expect(detail).toContainText("45 min");await expect(detail).toContainText("Ejercicios · demo");await expect(detail).toContainText("25 min");await expect(detail).toContainText("Fórmulas · formula-map");await expect(detail).toContainText("10 min");
});
