import {test,expect} from "@playwright/test";
const openPhysics=async page=>{await page.goto("/");await page.waitForFunction(()=>document.documentElement.dataset.appReady==="true");await expect(page.locator("#newNoteBtn")).toBeHidden();await page.locator('[data-open="fisica1"]').first().click();await page.locator("#studyUnit").selectOption("resumen-integral");const button=page.locator("#newNoteBtn");await expect(button).toBeVisible();await expect(button).toBeEnabled()};
const drag=async(page,locator,dx,dy)=>{const box=await locator.boundingBox();await page.mouse.move(box.x+12,box.y+10);await page.mouse.down();await page.mouse.move(box.x+12+dx,box.y+10+dy,{steps:6});await page.mouse.up()};

test("@desktop botón fijo, creación, arrastre preciso, libro y persistencia",async({page})=>{
  await openPhysics(page);const button=page.locator("#newNoteBtn"),before=await button.boundingBox();await page.locator(".content-pane").evaluate(element=>element.scrollTop=250);const after=await button.boundingBox();expect(after.x).toBeCloseTo(before.x,0);expect(after.y).toBeCloseTo(before.y,0);expect(await button.evaluate(element=>getComputedStyle(element).position)).toBe("fixed");
  await button.dblclick();await expect(page.locator(".note-window")).toHaveCount(1);await expect(page.locator(".note-window textarea")).toBeFocused();let record=await page.evaluate(()=>LBT_DB.getAll("notes").then(items=>items[0]));expect(record.anchor.type).toBe("free");expect(record).toEqual(expect.objectContaining({subjectId:"fisica1",unitId:"resumen-integral",tab:"summary",displayMode:"open"}));
  const note=page.locator(".note-window"),grip=note.locator(".note-grip"),initial=await note.boundingBox();const gripBox=await grip.boundingBox();await page.mouse.move(gripBox.x+37,gripBox.y+12);await page.mouse.down();await page.mouse.move(gripBox.x+38,gripBox.y+13);await page.mouse.up();const tapLike=await note.boundingBox();expect(tapLike.x).toBeCloseTo(initial.x,0);expect(tapLike.y).toBeCloseTo(initial.y,0);
  await drag(page,grip,95,120);const moved=await note.boundingBox();expect(moved.x-initial.x).toBeGreaterThan(70);expect(moved.y-initial.y).toBeGreaterThan(80);record=await page.evaluate(()=>LBT_DB.getAll("notes").then(items=>items[0]));expect(record.position.documentY).toBeGreaterThan(0);expect(record.position.xRatio).toBeGreaterThanOrEqual(0);expect(record.position.xRatio).toBeLessThanOrEqual(1);
  await page.getByRole("button",{name:"Minimizar"}).click();const book=page.locator(".note-book");await expect(book).toHaveCount(1);expect(await book.evaluate(element=>getComputedStyle(element).backgroundColor)).not.toBe("rgba(0, 0, 0, 0)");await drag(page,book,55,40);await expect(book).toHaveCount(1);await book.click();await expect(page.locator(".note-window textarea")).toBeFocused();
  await page.getByRole("button",{name:"Centrar nota"}).click();await page.reload();await page.locator('[data-open="fisica1"]').first().click();await page.locator("#studyUnit").selectOption("resumen-integral");await expect(page.locator(".note-window")).toHaveCount(1);
});

test.skip("@desktop selección, varias notas, teclado y compatibilidad histórica",async({page})=>{
  await openPhysics(page);await page.evaluate(()=>{const node=document.querySelector('[data-block-id="fisica1:demo:demo-intro"]'),range=document.createRange();range.selectNodeContents(node);const selection=getSelection();selection.removeAllRanges();selection.addRange(range)});await page.locator("#newNoteBtn").click();let records=await page.evaluate(()=>LBT_DB.getAll("notes"));expect(records[0].anchor.targetId).toBe("fisica1:demo:demo-intro");
  await page.waitForTimeout(500);await page.locator("#newNoteBtn").click();await expect(page.locator(".note-window")).toHaveCount(2);const first=page.locator(".note-window").first();await first.focus();const x=await first.boundingBox();await first.press("Shift+ArrowRight");const moved=await first.boundingBox();expect(moved.x-x.x).toBeGreaterThan(15);await first.press("Escape");await expect(page.locator(".note-book")).toHaveCount(1);
  const stamp=new Date().toISOString();await page.evaluate(async stamp=>{await LBT_DB.put("notes",{id:"legacy",subjectId:"fisica1",unitId:"demo",tab:"summary",anchor:{type:"free",targetId:null,exact:"",prefix:"",suffix:""},position:{x:.25,y:.3},text:"Histórica",color:"yellow",collapsed:true,createdAt:stamp,updatedAt:stamp,deletedAt:null});await LBT_NOTES.reload()},stamp);await expect(page.locator('.note-book[data-id="legacy"]')).toBeVisible();const legacy=await page.evaluate(()=>LBT_DB.get("notes","legacy"));expect(legacy.position.x).toBe(.25);
});

test("@desktop auto-scroll, una escritura final, zoom, visor y fullscreen",async({page})=>{
  await openPhysics(page);await page.locator("#newNoteBtn").click();await page.evaluate(()=>{window.__noteWrites=0;const original=LBT_DB.put.bind(LBT_DB);LBT_DB.put=async(store,value)=>{if(store==="notes")window.__noteWrites++;return original(store,value)}});const pane=page.locator(".content-pane");await pane.evaluate(element=>{element.querySelector(".content-card").style.minHeight="1800px";LBT_NOTES.reflow()});const grip=page.locator(".note-grip"),box=await grip.boundingBox(),paneBox=await pane.boundingBox();await page.mouse.move(box.x+15,box.y+12);await page.mouse.down();await page.mouse.move(paneBox.x+80,paneBox.y+paneBox.height-4,{steps:8});await page.waitForTimeout(600);await page.mouse.up();expect(await pane.evaluate(element=>element.scrollTop)).toBeGreaterThan(0);expect(await page.evaluate(()=>window.__noteWrites)).toBe(1);
  await page.locator("#zoomBtn").click();await page.evaluate(()=>LBT_NOTES.reflow());const noteBox=await page.locator(".note-window").boundingBox();const contentBox=await pane.boundingBox();expect(noteBox.x).toBeGreaterThanOrEqual(contentBox.x);expect(noteBox.x).toBeLessThan(contentBox.x+contentBox.width);await page.locator("#fullscreenBtn").click();await expect.poll(()=>page.evaluate(()=>!!document.fullscreenElement)).toBeTruthy();await page.evaluate(()=>document.exitFullscreen());
});

test.skip("@desktop modo lectura independiente, persistente y compatible con resaltados y notas",async({page})=>{
  await openPhysics(page);await page.locator("#readingSettingsBtn").click();await page.locator("#readingScope").selectOption("subject");for(const name of ["narrow","wideLine","large","hideSecondary","contrast","ruler","focus"]){await page.locator(`#readingPanel input[name="${name}"]`).check();await expect(page.locator("html")).toHaveClass(new RegExp(`reading-${name}`))}await expect(page.locator(".reading-ruler-line")).toBeVisible();await page.locator("#readingNext").click();await expect(page.locator(".reading-current")).toHaveCount(1);
  await page.locator("#newNoteBtn").click();await expect(page.locator(".note-window")).toBeVisible();await page.evaluate(()=>{const node=document.querySelector('[data-block-id="fisica1:demo:demo-intro"]'),range=document.createRange();range.selectNodeContents(node);const selection=getSelection();selection.removeAllRanges();selection.addRange(range)});await page.locator("#highlightBtn").click();await expect(page.locator("mark.study-highlight")).toHaveCount(1);
  await page.reload();await page.locator('[data-open="fisica1"]').first().click();await expect(page.locator("html")).toHaveClass(/reading-large/);expect(await page.evaluate(()=>LBT_DB.get("kv","settings").then(item=>!!item.value.readingBySubject.fisica1))).toBeTruthy();
});

test("@desktop @mobile modo lectura ocupa el viewport disponible",async({page})=>{
  await openPhysics(page);await page.locator("#readingBtn").click();
  await expect(page.locator("html")).toHaveClass(/immersive-reading/);
  const sizes=await page.evaluate(()=>{const viewport={width:innerWidth,height:innerHeight},study=document.querySelector("#studyPage").getBoundingClientRect(),pane=document.querySelector(".content-pane").getBoundingClientRect();return{viewport,study:{width:study.width,height:study.height,top:study.top,left:study.left},pane:{width:pane.width,height:pane.height,top:pane.top,left:pane.left},tabs:getComputedStyle(document.querySelector("#studyTabs")).display}});
  expect(sizes.study).toEqual({width:sizes.viewport.width,height:sizes.viewport.height,top:0,left:0});
  expect(sizes.pane).toEqual({width:sizes.viewport.width,height:sizes.viewport.height,top:0,left:0});
  expect(sizes.tabs).toBe("none");
  await page.locator("#readingModeExit").click();await expect(page.locator("html")).not.toHaveClass(/immersive-reading/);
});

test("@mobile touch, viewport, scroll normal y safe area",async({page})=>{
  await openPhysics(page);const button=page.locator("#newNoteBtn");expect(await button.evaluate(element=>getComputedStyle(element).bottom)).not.toBe("auto");await button.click();const grip=page.locator(".note-grip");expect(await grip.evaluate(element=>getComputedStyle(element).touchAction)).toBe("none");await drag(page,grip,-80,110);await page.setViewportSize({width:740,height:430});await page.evaluate(()=>LBT_NOTES.reflow());const box=await page.locator(".note-window").boundingBox();expect(box.x).toBeGreaterThanOrEqual(0);expect(box.y).toBeGreaterThanOrEqual(0);const pane=page.locator(".content-pane"),start=await pane.evaluate(element=>element.scrollTop);await pane.evaluate(element=>element.scrollTop+=120);expect(await pane.evaluate(element=>element.scrollTop)).toBeGreaterThanOrEqual(start);
});
