import {test,expect} from "@playwright/test";
async function openCards(page){await page.goto("/");await expect.poll(()=>page.evaluate(()=>typeof document.querySelector('[data-page="subjects"]')?.onclick==="function")).toBe(true);await page.locator('[data-page="subjects"]').click();await page.locator('.plan-course-main[data-open="quimica_organica"]').click();await page.getByRole("button",{name:"Tarjetas"}).click();await expect(page.getByRole("heading",{name:"Tarjetas de estudio"})).toBeVisible()}
async function startAlcanos(page,mode=/Memorizar/){await openCards(page);await page.getByRole("button",{name:mode}).click();const unit=page.locator('[data-unit="alcanos"]');await unit.check();await expect(page.locator("[data-start]")).toBeEnabled();await page.locator("[data-start]").click();await expect(page.locator(".organic-card")).toBeVisible()}

test("@desktop selector jerárquico permite parcial, todo y limpiar",async({page})=>{await openCards(page);await page.getByRole("button",{name:/Combinar ambos bancos/}).click();await expect(page.locator("[data-unit]")).toHaveCount(14);await page.locator('[data-unit="alquenos"]').check();await page.locator('[data-unit="aromaticos"]').check();await expect(page.locator("[data-start]")).toBeEnabled();await page.locator("[data-clear]").click();await expect(page.locator("[data-start]")).toBeDisabled();await page.locator("[data-select-all]").click();await expect(page.locator("[data-start]")).toBeEnabled();const topic=page.locator('[data-topic^="alquenos|"]').first();await topic.uncheck();await expect(page.locator('[data-unit="alquenos"]')).not.toBeChecked()});

test("@desktop gira, clasifica, deshace y persiste sin mostrar pistas",async({page})=>{await startAlcanos(page);await expect(page.locator(".organic-front p")).toBeVisible();await expect(page.locator(".organic-front")).not.toContainText(/Hidrogenación de alquenos:/);await page.locator(".organic-card").press("Space");await expect(page.locator(".organic-card")).toHaveClass(/flipped/);await page.getByRole("button",{name:"Bien",exact:true}).click();await expect(page.getByText(/1 de .* clasificadas/)).toBeVisible();await page.locator("[data-undo]").click();await expect(page.getByText(/0 de .* clasificadas/)).toBeVisible();await page.reload();await page.locator('[data-open="quimica_organica"]').first().click();await page.getByRole("button",{name:"Tarjetas"}).click();await expect(page.locator(".organic-card")).toBeVisible()});

test("@desktop gestos, teclado, enlace profundo y portapapeles",async({page,context})=>{await context.grantPermissions(["clipboard-read","clipboard-write"]);await startAlcanos(page);let card=page.locator(".organic-card");await card.click();await page.locator(".organic-clipboard-toggle").click();await page.locator("[data-copy-current]").click();await expect.poll(()=>page.evaluate(()=>navigator.clipboard.readText())).toContain("Pregunta:");await card.press("ArrowDown");await expect(page.getByText(/1 de .* clasificadas/)).toBeVisible();await page.locator("[data-undo]").click();await expect(page.getByText(/0 de .* clasificadas/)).toBeVisible();await card.click();const box=await card.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+120,box.y+box.height/2);await page.mouse.up();await expect(page.getByText(/1 de .* clasificadas/)).toBeVisible();await page.reload();await page.locator('[data-open="quimica_organica"]').first().click();await page.getByRole("button",{name:"Tarjetas"}).click();card=page.locator(".organic-card");await card.click();await expect(card).toHaveClass(/flipped/);await page.locator("[data-summary-target]").click();await expect.poll(()=>page.evaluate(()=>sessionStorage.getItem("organic-card-return"))).toBe("1");await expect(page.locator(".rich-document")).toBeVisible({timeout:10000});await expect(page.locator("#organicReturnToCard")).toBeVisible();await page.locator("#organicReturnToCard").click();await expect(page.locator(".organic-card")).toBeVisible()});

test("@desktop resultados separan bien, mal y repasar",async({page})=>{await startAlcanos(page);await page.locator(".organic-card").click();await page.getByRole("button",{name:"Mal",exact:true}).click();await page.locator("[data-finish]").click();await expect(page.getByRole("heading",{name:"Resumen de la sesión"})).toBeVisible();await expect(page.locator(".organic-result-grid")).toContainText("Mal");await expect(page.getByRole("button",{name:"Repetir incorrectas"})).toBeEnabled()});

test("@mobile mantiene giro, botones y selector utilizables",async({page})=>{await startAlcanos(page,/Practicar síntesis/);await page.locator(".organic-card").tap();await expect(page.locator(".organic-card")).toHaveClass(/flipped/);await expect(page.locator(".organic-grade-actions")).toBeVisible();await page.getByRole("button",{name:"Repasar",exact:true}).tap();await expect(page.getByText(/1 de .* clasificadas/)).toBeVisible()});
