import assert from "node:assert/strict";import fs from "node:fs";import os from "node:os";import path from "node:path";import {execFileSync} from "node:child_process";import {validateUnit,root} from "../factory/validators/lib.mjs";
const organica=path.join(root,"content/subjects/quimica_organica/units/resumen-integral");assert.deepEqual(validateUnit(organica),[],"acepta la unidad enriquecida de Química Orgánica");const rich=JSON.parse(fs.readFileSync(path.join(organica,"rich.json"))),assets=JSON.parse(fs.readFileSync(path.join(organica,"assets.json")));assert.equal(rich.blocks.filter(x=>x.type==="details").length,419);assert.equal(assets.assets.length,249);assert.ok(assets.assets.every(asset=>fs.existsSync(path.join(organica,asset.path))));const unsafe=[];(function inspect(value){if(Array.isArray(value))return value.forEach(inspect);if(value&&typeof value==="object")for(const [key,item] of Object.entries(value)){if(key==="html"||key==="script"||/^on[a-z]+$/i.test(key))unsafe.push(key);inspect(item)}else if(typeof value==="string"&&(/^data:image\//i.test(value)||/<script[\s>]/i.test(value)))unsafe.push(value)})(rich);assert.deepEqual(unsafe,[],"el contenido importado no conserva código ni imágenes base64");
const example=path.join(root,"content/subjects/fisica1/units/demo");assert.deepEqual(validateUnit(example),[],"acepta el paquete mínimo válido");
const temp=fs.mkdtempSync(path.join(os.tmpdir(),"lbt-content-"));fs.cpSync(example,temp,{recursive:true});fs.rmSync(path.join(temp,"cards.json"));assert.ok(validateUnit(temp).some(x=>x.includes("Falta cards.json")),"rechaza archivos faltantes");fs.rmSync(temp,{recursive:true,force:true});
const badRef=fs.mkdtempSync(path.join(os.tmpdir(),"lbt-content-"));fs.cpSync(example,badRef,{recursive:true});const summary=JSON.parse(fs.readFileSync(path.join(badRef,"summary.json")));summary.blocks[0].references[0].sourceId="missing";fs.writeFileSync(path.join(badRef,"summary.json"),JSON.stringify(summary));assert.ok(validateUnit(badRef).some(x=>x.includes("referencia inexistente")));fs.rmSync(badRef,{recursive:true,force:true});
const badExercise=fs.mkdtempSync(path.join(os.tmpdir(),"lbt-content-"));fs.cpSync(example,badExercise,{recursive:true});const exercises=JSON.parse(fs.readFileSync(path.join(badExercise,"exercises.json")));exercises.exercises[0].origin="generated";fs.writeFileSync(path.join(badExercise,"exercises.json"),JSON.stringify(exercises));assert.ok(validateUnit(badExercise).some(x=>x.includes("falta basedOn")));fs.rmSync(badExercise,{recursive:true,force:true});
const badSchema=fs.mkdtempSync(path.join(os.tmpdir(),"lbt-content-"));fs.cpSync(example,badSchema,{recursive:true});const manifest=JSON.parse(fs.readFileSync(path.join(badSchema,"package.json")));manifest.unexpected=true;fs.writeFileSync(path.join(badSchema,"package.json"),JSON.stringify(manifest));assert.ok(validateUnit(badSchema).some(x=>x.includes("additional properties")),"Ajv rechaza additionalProperties aunque pasen los controles cruzados");fs.rmSync(badSchema,{recursive:true,force:true});
const node=process.execPath,catalog=path.join(root,"content/catalog.json");execFileSync(node,[path.join(root,"factory/validators/content-catalog.mjs")]);const first=fs.readFileSync(catalog,"utf8");execFileSync(node,[path.join(root,"factory/validators/content-catalog.mjs")]);assert.equal(fs.readFileSync(catalog,"utf8"),first,"el catálogo es determinista");
const createRoot=path.join(root,"content/subjects/test-factory");try{execFileSync(node,[path.join(root,"factory/validators/content-new.mjs"),"--subject","test-factory","--unit","unit-test","--title","Unidad de prueba"]);assert.equal(validateUnit(path.join(createRoot,"units/unit-test")).length,0,"content:new crea una unidad válida");execFileSync(node,[path.join(root,"factory/validators/content-catalog.mjs")]);const catalog=JSON.parse(fs.readFileSync(path.join(root,"content/catalog.json")));assert.ok(!catalog.packages.some(item=>item.subjectId==="test-factory"),"el catálogo excluye paquetes draft");assert.equal(catalog.packages.filter(item=>item.subjectId==="fisica1").length,3,"publica tres unidades de Física I")}finally{fs.rmSync(createRoot,{recursive:true,force:true});execFileSync(node,[path.join(root,"factory/validators/content-catalog.mjs")])}
console.log("Fábrica y validación de contenido: OK");
