const assert=require("node:assert/strict");
const fs=require("node:fs");
const vm=require("node:vm");
const source=fs.readFileSync("js/utilities.js","utf8");
const context={window:{},crypto:require("node:crypto").webcrypto,console,setInterval:()=>1,clearInterval:()=>{},CustomEvent:class{}};
vm.createContext(context);vm.runInContext(source,context);
const U=context.window.LBT_UTILS;
assert.equal(U.normalize("Fórmulas y MOLÉCULAS"),"formula y molecula");
assert.ok(U.score("mitocondria","mitocondrias")>.7,"tolera flexiones simples");
assert.ok(U.score("mitocondira","mitocondria")>=.55,"tolera una transposición tipográfica");
assert.equal(U.score("xyz","mitocondria"),0,"no inventa coincidencias");
const items=[{contentType:"card",targetId:"1"},{contentType:"card",targetId:"1"},{contentType:"formula",targetId:"2"},{contentType:"summary",targetId:"3"}];
assert.deepEqual(JSON.parse(JSON.stringify(U.sample(items,3,42))),JSON.parse(JSON.stringify(U.sample(items,3,42))),"la misma semilla reproduce el mazo");
assert.equal(U.sample(items,10,42).length,3,"el repaso elimina duplicados");
assert.equal(U.shouldStopDetectedStudy({last:1000,current:75999,idleMs:75000}),false,"la actividad reciente sigue contando");
assert.equal(U.shouldStopDetectedStudy({last:1000,current:76000,idleMs:75000}),true,"la inactividad corta la sesión");
assert.equal(U.shouldStopDetectedStudy({hidden:true,last:1000,current:2000,idleMs:75000}),true,"una pestaña en background corta la sesión");
assert.match(source,/Math\.floor\(Date\.now\(\)\/300000\)/,"la actividad se deduplica en ventanas de cinco minutos");
assert.match(source,/navigator\.locks\?\.request/,"una sesión activa se coordina con Web Locks cuando está disponible");
const db=fs.readFileSync("js/db.js","utf8");
assert.match(db,/store!=="studySessions"\|\|\["finished","cancelled"\]/,"los respaldos excluyen sesiones activas");
const sync=fs.readFileSync("js/sync.js","utf8");
for(const store of ["studySessions","activityLog"])assert.ok(sync.includes(store),`Drive debe incluir ${store}`);
console.log("Pruebas de utilidades de estudio: OK");
