import fs from "node:fs";import path from "node:path";import Ajv2020 from "ajv/dist/2020.js";import addFormats from "ajv-formats";
export const root=path.resolve(import.meta.dirname,"../..");
export const fileNames=["package.json","summary.json","glossary.json","cards.json","exercises.json","map.json","sources.json"];
export const mojibake=new RegExp("\\u00c3.|\\u00c2.|\\u00e2(?:\\u20ac|\\u2026)|\\uFFFD","u");
export const read=p=>JSON.parse(fs.readFileSync(p,"utf8"));
const schemaFiles=Object.fromEntries(fileNames.map(name=>[name,read(path.join(root,"factory/schemas",name.replace(".json",".schema.json")))]));
const ajv=new Ajv2020({allErrors:true,strict:true});addFormats(ajv);const schemaValidators=Object.fromEntries(Object.entries(schemaFiles).map(([name,schema])=>[name,ajv.compile(schema)]));
for(const name of ["rich.json","assets.json"]){const schema=read(path.join(root,"factory/schemas",name.replace(".json",".schema.json")));schemaValidators[name]=ajv.compile(schema)}
export const refs=value=>{const out=[];const visit=x=>{if(Array.isArray(x))x.forEach(visit);else if(x&&typeof x==="object"){if(typeof x.sourceId==="string")out.push(x);Object.values(x).forEach(visit)}};visit(value);return out};
export function unitDirs(base=path.join(root,"content/subjects")){if(!fs.existsSync(base))return[];const out=[];for(const subject of fs.readdirSync(base).sort()){const units=path.join(base,subject,"units");if(!fs.existsSync(units))continue;for(const unit of fs.readdirSync(units).sort())if(fs.statSync(path.join(units,unit)).isDirectory())out.push(path.join(units,unit))}return out}
export function validateUnit(dir){const errors=[];for(const name of fileNames)if(!fs.existsSync(path.join(dir,name)))errors.push(`Falta ${name}`);if(errors.length)return errors;const data=Object.fromEntries(fileNames.map(n=>[n,read(path.join(dir,n))])),pkg=data["package.json"];
 for(const name of fileNames){const validate=schemaValidators[name];if(!validate(data[name]))for(const error of validate.errors||[])errors.push(`${name}${error.instancePath||"/"}: ${error.message}`)}
 const required=["packageSchemaVersion","factoryVersion","contentStandard","subjectId","unitId","title","contentVersion","status","generatedAt","reviewedAt","files"];for(const k of required)if(!(k in pkg))errors.push(`package.json: falta ${k}`);if(pkg.packageSchemaVersion!==1)errors.push("packageSchemaVersion desconocido");if(!["draft","reviewed","published"].includes(pkg.status))errors.push("status desconocido");
 const collections=[["summary.json","blocks"],["glossary.json","entries"],["cards.json","cards"],["exercises.json","exercises"],["map.json","nodes"],["map.json","edges"],["sources.json","sources"]];const ids=new Map();for(const [f,k] of collections){if(!Array.isArray(data[f]?.[k])){errors.push(`${f}: ${k} debe ser array`);continue}for(const item of data[f][k])if(item?.id){if(ids.has(item.id))errors.push(`ID duplicado: ${item.id}`);ids.set(item.id,f)}}
 const sources=new Set((data["sources.json"].sources||[]).map(x=>x.id));for(const [name,value] of Object.entries(data))for(const r of refs(value)){if(!sources.has(r.sourceId))errors.push(`${name}: referencia inexistente ${r.sourceId}`);if(r.page!==undefined&&(!Number.isInteger(r.page)||r.page<1))errors.push(`${name}: página inválida`);if(r.pageStart!==undefined&&(!Number.isInteger(r.pageStart)||r.pageStart<1||!Number.isInteger(r.pageEnd)||r.pageEnd<r.pageStart))errors.push(`${name}: rango inválido`)}
 const exerciseById=new Map((data["exercises.json"].exercises||[]).map(exercise=>[exercise.id,exercise]));for(const ex of exerciseById.values()){if(!["source","generated"].includes(ex.origin))errors.push(`Ejercicio ${ex.id}: origen desconocido`);if(ex.origin==="generated"&&(!Array.isArray(ex.basedOn)||!ex.basedOn.length))errors.push(`Ejercicio generado ${ex.id}: falta basedOn`);for(const id of ex.basedOn||[]){if(id===ex.id)errors.push(`Ejercicio ${ex.id}: autorreferencia`);else if(!exerciseById.has(id))errors.push(`Ejercicio ${ex.id}: basedOn debe referir a ejercicio source existente ${id}`);else if(exerciseById.get(id).origin!=="source")errors.push(`Ejercicio ${ex.id}: basedOn ${id} no es source`)}}
 const formulaBlocks=(data["summary.json"].blocks||[]).filter(x=>x.kind==="formula");for(const f of formulaBlocks){if(!f.visual||!f.linear||!Array.isArray(f.variables)||!f.variables.length||f.variables.some(variable=>!variable.symbol||!variable.definition))errors.push(`Fórmula ${f.id}: representación o variables no definidas`);for(const id of f.relatedExercises||[])if(!exerciseById.has(id))errors.push(`Fórmula ${f.id}: ejercicio relacionado inexistente ${id}`)}
 const mapIds=new Set((data["map.json"].nodes||[]).map(x=>x.id));for(const e of data["map.json"].edges||[]){if(!mapIds.has(e.from)||!mapIds.has(e.to))errors.push("Mapa: conexión inexistente");if(!["cause","consequence","belongs-to","calculated-with","differs-from","requires","produces","related-to","applied-in"].includes(e.type))errors.push("Mapa: tipo desconocido")}
 for(const name of ["rich.json","assets.json"]){const file=path.join(dir,name);if(!fs.existsSync(file))continue;const value=read(file),validate=schemaValidators[name];if(!validate(value))for(const error of validate.errors||[])errors.push(`${name}${error.instancePath||"/"}: ${error.message}`);if(mojibake.test(fs.readFileSync(file,"utf8")))errors.push(`${name}: posible mojibake`)}for(const name of fileNames){const text=fs.readFileSync(path.join(dir,name),"utf8");if(mojibake.test(text))errors.push(`${name}: posible mojibake`)}return errors}
