plugins {
    id 'com.android.application'
}

android {
    namespace 'com.solved.quimicageneral'
    compileSdk 35

    defaultConfig {
        applicationId 'com.solved.quimicageneral'
        minSdk 24
        targetSdk 35
        versionCode 2
        versionName '0.2.0-apk'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
